# Configuration for the FMPB

[options]
    require_manual_disambiguation = true

[divisions]

    #Men's divisions 
    mropen = {name ="MR-O",min=0,max=999,equipment="Raw",sex="M"}
    mopen = {name ="M-O",min=0,max=999,equipment="Single-ply",sex="M"}
    mru23 = {name ="MR-Jr",min=14,max=22.5,equipment="Raw",sex="M"}
    mu23 = {name ="M-Jr",min=14,max=22.5,equipment="Single-ply",sex="M"}
    mru18 = {name ="MR-Sj",min=14,max=17.5,equipment="Raw",sex="M"}
    mu18 = {name ="M-Sj",min=14,max=17.5,equipment="Single-ply",sex="M"}
    mrm1 = {name ="MR-M1",min=39.5,max=48.5,equipment="Raw",sex="M"}
	mwm1 = {name ="MW-M1",min=0,max=999,equipment="Wraps",sex="M"}
    mm1 = {name ="M-M1",min=39.5,max=48.5,equipment="Single-ply",sex="M"}
    mrm2 = {name ="MR-M2",min=49.5,max=58.5,equipment="Raw",sex="M"}
    mm2 = {name ="M-M2",min=49.5,max=58.5,equipment="Single-ply",sex="M"}
    mrm3 = {name ="MR-M3",min=59.5,max=68.5,equipment="Raw",sex="M"}
    mm3 = {name ="M-M3",min=59.5,max=68.5,equipment="Single-ply",sex="M"}
    mrm4 = {name ="MR-M4",min=69.5,max=999,equipment="Raw",sex="M"}
    mm4 = {name ="M-M4",min=69.5,max=999,equipment="Single-ply",sex="M"}
    mrm5 = {name ="MR-M5",min=79.5,max=999,equipment="Raw",sex="M"}
    mm5 = {name ="M-M5",min=79.5,max=999,equipment="Single-ply",sex="M"}

    #Women's divisions
    fropen = {name ="FR-O",min=0,max=999,equipment="Raw",sex="F"}
    fopen = {name ="F-O",min=0,max=999,equipment="Single-ply",sex="F"}
    fru23 = {name ="FR-Jr",min=14,max=22.5,equipment="Raw",sex="F"}
    fu23 = {name ="F-Jr",min=14,max=22.5,equipment="Single-ply",sex="F"}
    fru18 = {name ="FR-Sj",min=14,max=17.5,equipment="Raw",sex="F"}
    fu18 = {name ="F-Sj",min=14,max=17.5,equipment="Single-ply",sex="F"}
    frm1 = {name ="FR-M1",min=39.5,max=48.5,equipment="Raw",sex="F"}
    fm1 = {name ="F-M1",min=39.5,max=48.5,equipment="Single-ply",sex="F"}
    frm2 = {name ="FR-M2",min=49.5,max=58.5,equipment="Raw",sex="F"}
    fm2 = {name ="F-M2",min=49.5,max=58.5,equipment="Single-ply",sex="F"}
    frm3 = {name ="FR-M3",min=59.5,max=68.5,equipment="Raw",sex="F"}
    fm3 = {name ="F-M3",min=59.5,max=68.5,equipment="Single-ply",sex="F"}
    frm4 = {name ="FR-M4",min=69.5,max=999,equipment="Raw",sex="F"}
    fm4 = {name ="F-M4",min=69.5,max=999,equipment="Single-ply",sex="F"}
    frm5 = {name ="FR-M5",min=79.5,max=999,equipment="Raw",sex="F"}
    fm5 = {name ="F-M5",min=79.5,max=999,equipment="Single-ply",sex="F"}

    #Misc divisions
    mrg = {name ="MR-G",min=0,max=999,equipment="Raw",place="G",sex="M"}
    mg = {name ="M-G",min=0,max=999,equipment="Single-ply",place="G",sex="M"}
    frg = {name ="FR-G",min=0,max=999,equipment="Raw",place="G",sex="F"}
    fg = {name ="F-G",min=0,max=999,equipment="Single-ply",place="G",sex="F"}
    mxrg = {name ="MxR-G",min=0,max=999,equipment="Raw",place="G",sex="M"}
    mxg = {name ="Mx-G",min=0,max=999,equipment="Single-ply",place="G",sex="M"}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-12-31"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["MR-Jr","MR-Sj","M-Jr","M-Sj"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-01-01"]
    sex = "F"
    divisions = ["FR-Jr","FR-Sj","F-Jr","F-Sj"]


[exemptions]
