#!/bin/bash

set -e

if [ $# -ne 1 ]; then
	echo " Usage :$0 http://url/to/results/page"
	exit 1
fi

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

# Download the website to original.html
wget --output-document=original.html "$1"
echo "$1" > URL

# Sometimes the documents are encoded in ISO-8859-1.
file original.html | grep ISO-8859 && iconv -f ISO-8859-1 -t UTF-8 original.html > original2.html
if [ -f original2.html ]; then
        mv original2.html original.html
fi

# The HTML is grotesquely malformed, and BeautifulSoup can't parse it.
# But LibreOffice's parser is very forgiving, so we just use that.
# Creates original.csv.
dos2unix original.html
mv original.html original.xls
libreoffice --headless --convert-to csv original.xls

# If CSV conversion completed successfully, remove the intermediary
# files early to benefit terminal autocompletion.
if [ -f original.csv ]; then
	rm original.xls
fi

cp "${SCRIPTDIR}/../meet.template" "meet.csv"

# Commands after this point were extracted into a separate file
# since they had to be re-run by hand in case of error.
${SCRIPTDIR}/wabdl-parse-post
