#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new meets from the WPAU
#


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request

URLS = ["http://wpa-ukraine.com/rezultaty/"]
BASEURL = "http://wpa-ukraine.com/"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    div = soup.find("div", {"class": "art-PostContent"})
    urls = []
    for a in div.find_all('a'):
        url = a['href']

        if not 'http' in url:
            url = BASEURL + url
            url = url.replace('.com//','/')
        if not url in urls:
            urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    meetlist = []
    for url in URLS:
        html = gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    known = getenteredurls()

    for m in meetlist:
        if not m in known:
            print(color('[WPA-UKR] ') + m)


if __name__ == '__main__':
    main()
