#!/bin/bash
#
# Script to take data from fetch and import it into the directory.
# Still done one-by-one so that there's some manual oversight.
#

set -e

if [ $# -ne 1 ]; then
	echo " Usage: $0 meetnum"
	exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir "${DIR}/$1"
mv "${DIR}/fetch/$1"* "${DIR}/$1"

cd "${DIR}/$1"
mv *meet* meet.csv
${DIR}/uspa-parse "$1.pdf"
rm "$1.pdf"

git add original.txt entries.csv meet.csv
