#!/bin/bash

set -e

if [ $# -ne 1 ]; then
	echo " Usage: $0 uspa-results.pdf"
	exit 1
fi

BASENAME=${1%.pdf}
CSVFILE=${BASENAME}.csv
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

# Make the results.txt.
pdftotext -layout "$1"
mv ${BASENAME}.txt results.txt

# Creates some HTML file.
${SCRIPTDIR}/uspa-pdf-to-bbox "$1"
${SCRIPTDIR}/uspa-bbox-to-csv ${BASENAME}.html > ${CSVFILE}
${SCRIPTDIR}/uspa-csv-to-final ${CSVFILE} > lifters.csv

# Always recalculate the Wilks, since USPA uses age coefficients.
${REPOSCRIPTDIR}/fix-wilks lifters.csv

rm ${BASENAME}.html
rm ${CSVFILE}
