#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Check if there are any new USPA results on the download page.


from bs4 import BeautifulSoup
import os
import shutil
import sys
import urllib.request


CUTOFF = 200  # Ignore earlier meets, since they have invalid URLs anyway.
RESULTSURL = 'https://docs.google.com/spreadsheets/d/1HBpedvVS8N0H75Eg9qwTxClqtV1EqO-IuctYzgiyMNI/pubhtml/sheet?hl=en_US&headers=false&gid=0'
USPADIR = os.path.dirname(os.path.realpath(__file__))


def color(s):
    return "\033[1;34m" + s + "\033[0;m"


# Just a way to name a tuple.
class Meet:

    def __init__(self, url, num, date, name, location):
        self.url = url
        self.num = ("0" * (4 - len(num))) + num
        self.date = date
        self.name = name
        self.location = location

    def __str__(self):
        return '"%s - %s %s %s"' % (self.num, self.date, self.name, self.location)

    def __repr__(self):
        return str(self)


def gethtml():
    with urllib.request.urlopen(RESULTSURL) as r:
        return r.read()


def getmeetinfo(tr):
    # The first column would have the URL.
    urltd = tr.find('td')
    if urltd == None:
        return None

    a = urltd.find('a')
    if a == None:
        return None
    url = a.get('href')

    # Then the rest of the information should be there too.
    tds = tr.find_all('td')
    num = tds[1].get_text()
    date = tds[2].get_text()
    name = tds[3].get_text()
    location = tds[4].get_text()

    return Meet(url, num, date, name, location)


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    # Ignore all the Google Sheets javascript and get to the tags.
    doc = soup.find(id='sheets-viewport')
    table = doc.find('table')

    meets = []

    # Iterate over every row of the table.
    for tr in table.find_all('tr'):
        info = getmeetinfo(tr)
        if info:
            meets.append(info)

    return meets


def getknownmeets():
    # Known meets for the USPA have numeric directory names.
    meets = []
    for name in os.listdir(USPADIR):
        if name.isdigit():
            meets.append(name)
    return meets


def getunknownmeets(meets, known):
    unknown = []
    for meet in meets:
        if meet.num not in known and int(meet.num) >= CUTOFF:
            unknown.append(meet)
    return unknown


def main():
    html = gethtml()
    meets = getmeetlist(html)
    known = getknownmeets()
    remote = getunknownmeets(meets, known)

    for meet in remote:
        print(color('[USPA] ') + meet.url)


if __name__ == '__main__':
    main()
