#!/bin/bash

set -e

if [ $# -ne 1 ]; then
	echo " Usage: $0 uspa-results.pdf"
	exit 1
fi

BASENAME=${1%.pdf}
CSVFILE=${BASENAME}.csv
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

# Make the original.txt.
pdftotext -layout "$1"
mv ${BASENAME}.txt original.txt

# Creates some HTML file.
${SCRIPTDIR}/uspa-pdf-to-bbox "$1"
${SCRIPTDIR}/uspa-bbox-to-csv ${BASENAME}.html > ${CSVFILE}
${SCRIPTDIR}/uspa-csv-to-final ${CSVFILE} > entries.csv

# Don't store Wilks, since it will be recalculated.
${REPOSCRIPTDIR}/csv-rmcol entries.csv Wilks

rm ${BASENAME}.html
rm ${CSVFILE}
