#!/bin/bash

set -e

if [ $# -ne 1 ]; then
	echo " Usage: $0 uspa-results.pdf"
	exit 1
fi

CSVFILE=`mktemp`
BASENAME=${1%.pdf}

# Creates some HTML file.
./uspa-pdf-to-bbox "$1"
./uspa-bbox-to-csv ${BASENAME}.html > ${CSVFILE}
./uspa-csv-to-final ${CSVFILE} > ${BASENAME}-lifters.csv

rm ${BASENAME}.html
rm ${CSVFILE}
