#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes the CPU main page for new meets.
# The CPU updated their website and removed raw database access.
#
# On the new site, in order to look up a meet in the database, you need
# to either already know its full name or know a lifter in that meet.
# The CPU pulls a "Latest Results" list from the database and shows that on
# the main page. So we can use that to pick up some of the new ones.
# We would miss any meets that take a while to post.


from bs4 import BeautifulSoup
import sys
import os
from os.path import join, realpath, dirname

try:
    import oplprobe
except ImportError:
    sys.path.append(
        join(dirname(dirname(dirname(realpath(__file__)))), "scripts"))
    import oplprobe


FEDDIR = os.path.dirname(os.path.realpath(__file__))
FEDURL = "http://www.powerlifting.ca"

# The CPU website annoyingly posts results on per-province pages,
# so we have to scan them all individually.
#
# List from http://www.powerlifting.ca/cpu/index.php/contests/provincial-results
# Without "www." to appease the Python style checker due to long strings.
PROVINCE_URLS = [
    "http://powerlifting.ca/cpu/index.php/alberta",
    "http://powerlifting.ca/cpu/index.php/british-columbia",
    "http://powerlifting.ca/cpu/index.php/manitoba",
    "http://powerlifting.ca/cpu/index.php/newfoundland",
    "http://powerlifting.ca/cpu/index.php/new-brunswick",
    "http://powerlifting.ca/cpu/index.php/nova-scotia",
    "http://powerlifting.ca/cpu/index.php/ontario",
    "http://powerlifting.ca/cpu/index.php/prince-edward-island",
    "http://powerlifting.ca/cpu/index.php/quebec",
    "http://powerlifting.ca/cpu/index.php/saskatchewan",
    "http://powerlifting.ca/cpu/index.php/contests/national-results",
    "http://powerlifting.ca/cpu/index.php/contests/regional-results/eastern-canadians",
    "http://powerlifting.ca/cpu/index.php/contests/regional-results/western-canadians",
    "http://powerlifting.ca/cpu/index.php/contests/regional-results/central-canadians"
]


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;31m" + s + "\033[0;m"


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    urls = []
    for a in soup.find_all("a"):
        url = a['href']
        if '/contest-results' not in url:
            continue

        if url not in urls:
            urls.append(url)

    return urls


def main():
    meetlist = []

    # Scans from new meets from the homepage, which displays the five most
    # recent results, sorted by date. This skips old results.
    html = oplprobe.gethtml(FEDURL)
    meetlist = meetlist + getmeetlist(html)

    for url in PROVINCE_URLS:
        html = oplprobe.gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    entered = oplprobe.getenteredurls(FEDDIR)
    unentered = oplprobe.getunenteredurls(meetlist, entered)

    oplprobe.print_meets(color('[CPU]'), unentered)


if __name__ == '__main__':
    main()
