#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for meet results from the Commonwealth Powerlifting Federation.
# All the results are on a single page, very nice! Meets are very rare.


from bs4 import BeautifulSoup
import os
import sys
import urllib.request


FEDDIR = os.path.dirname(os.path.realpath(__file__))
URLS = ["http://commonwealthpowerlifting.com/results.html",
        "http://commonwealthpowerlifting.com/"]
BASEURL = "http://commonwealthpowerlifting.com/"


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;36m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    div = soup.find("div", {"id": "content"})

    urls = []
    for a in div.find_all('a'):
        url = a['href']

        if 'mailto:' in url:
            continue

        if 'http://' not in url:
            url = BASEURL + url

        if url not in urls:
            urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    meetlist = []

    for url in URLS:
        html = gethtml(url)
        meetlist = getmeetlist(html)

    known = getenteredurls()

    for m in meetlist:
        if m not in known:
            print(color('[CommonwealthPF] ') + m)


if __name__ == '__main__':
    main()
