[divisions]
    unknown = {name='',min=14,max=18}
	open = {name='Open',min=14,max=18}
    9 = {name="9", min=14, max=15}
    10 = {name="10", min=15, max=16}
    11 = {name="11", min=16, max=17}
    12 = {name="12", min=17, max=18}

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range=["0000-01-01","2021-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100", "100+"]
    date_range=["0000-01-01","2021-12-31"]
    sex = "F"

# LHSPLA now uses pounds classes with exact pound values.
[weightclasses.default_M]
    classes = ["52","56.5","60.1","67.5","75","82.5","90","100","110","125","125+"]
    date_range=["2022-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56.5","60.1","67.5","75","82.5","90","100", "100+"]
    date_range=["2022-01-01","9999-01-01"]
    sex = "F"
	
[exemptions]
    2401 = ["ExemptWeightClassConsistency"] # I could not get the 132lbs class to pass correctly
    2402 = ["ExemptWeightClassConsistency"] # I could not get the 132lbs class to pass correctly
    2403 = ["ExemptWeightClassConsistency"] # I could not get the 132lbs class to pass correctly
    2404 = ["ExemptWeightClassConsistency"] # I could not get the 132lbs class to pass correctly