#!/bin/bash

set -e

if [ $# -ne 2 ]; then
	echo " Usage: $0 dirname url"
	exit 1
fi

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"


mkdir "$1"
cd "$1"


if [[ $2 == *"1drv"* ]]; then
	${REPOSCRIPTDIR}/onedrive-downloader $2 "original.xlsx"
	# Convert the spreadsheet to HTML.
	# The spreadsheet will have multiple pages -- these will all be added to one document.
	libreoffice --headless --convert-to html "original.xlsx"
	EXTENSION="xlsx"
else
	# Remember whether it's XLS or XLSX.
	EXTENSION="${2##*.}"

	# Download the website to original.xls(s)
	wget --output-document="original.${EXTENSION}" "$2" 
	# Convert the spreadsheet to HTML.
	# The spreadsheet will have multiple pages -- these will all be added to one document.
	libreoffice --headless --convert-to html "original.${EXTENSION}"
fi

# Save the website URL for future use, since it's pretty hard to tell
# what meets on the site are tracked and which aren't.
echo "$2" > URL

# Convert the spreadsheet to HTML.
# The spreadsheet will have multiple pages -- these will all be added to one document.
libreoffice --headless --convert-to html "original.${EXTENSION}"

# Move the original.html to tmp.xls -- newer versions of LibreOffice don't
# understand how to convert HTML -> CSV, but do understand XLS -> CSV.
mv original.html tmp.xls


#Remove red font colour in front of <s> tags
sed -i -e 's/<s><font.*color="#FF0000">/-/g' tmp.xls
sed -i -e 's/<font face=.*color="#FF0000">/-/g' tmp.xls
sed -i -e 's/<\/font>//g' tmp.xls


# Convert <s> to "-".
sed -i -e 's/<s>/-/g' tmp.xls
sed -i -e 's/<\/s>//g' tmp.xls


#Remove sdvals from html, otherwise LibreOffice ignores negatives when converting to csv
sed -i -e 's/sdval="[^\"]*"//g' tmp.xls

# Convert commas in numbers to periods
sed -i -e 's/,/\./g' tmp.xls

# Convert the HTML back to CSV.
# The --infilter argument is necessary to get LibreOffice to stop parsing
# the encoding as ISO-8859-1, and preserve the UTF8 encoding.
# See https://bugs.documentfoundation.org/show_bug.cgi?id=36313#c17.
libreoffice --headless --convert-to csv --infilter=CSV:44,34,UTF8 tmp.xls
mv tmp.csv original.csv

# Remove some dash-only columns from the CSV.
sed -i -e 's/,-,/,,/g' original.csv
sed -i -e 's/,-,/,,/g' original.csv


#Clean up.
if [ -f original.csv ]; then
	rm tmp.xls original.${EXTENSION}
fi

${SCRIPTDIR}/wpc-rus-parse-post
