#!/bin/bash

set -e


if [ $# -ne 2 ]; then
	echo " Usage: $0 dirname http://url/to/results/page"
	exit 1
fi

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

mkdir "$1"
cd "$1"

# Save the website URL for future use, since it's pretty hard to tell
# what meets on the site are tracked and which aren't.
echo "$2" > URL

# Import the meet
${SCRIPTDIR}/spf-parse.py $2

# Commands after this point were extracted into a separate file
# since they had to be re-run by hand in case of error.
${SCRIPTDIR}/spf-import-post
