#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new meets from the NSF.


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request


URLS = ["http://styrkeloft.no/stevner/?page=protokoller",
        "http://styrkeloft.no/stevner/?page=protokoller&aar=2015"]
BASEURL = "http://styrkeloft.no/"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;31m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read().decode('utf-8')


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    urls = []
    for a in soup.find_all('a'):
        url = a['href']

        # Result visualization.
        if not 'page=protokoll_vis' in url:
            continue

        # Easy way to visually see EPF and IPF meets.
        klubb = a.next.next.next.next.text
        url = url + ' (%s)' % klubb

        if not 'http' in url:
            url = BASEURL + url
            url = url.replace('../', '')
        if not url in urls:
            urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    meetlist = []
    for url in URLS:
        html = gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    known = getenteredurls()

    for m in meetlist:
        if not m.split()[0] in known:
            print(color('[NSF] ') + m)
    print(color('[NSF] ') + "Continue working through archive.")


if __name__ == '__main__':
    main()
