#!/bin/sh

# From https://unix.stackexchange.com/questions/66097/find-all-files-with-a-python-shebang
PYTHONFILES=$(find . \( -type f -o -name "*.py" \) -exec awk '/^#!.*python/{print FILENAME} {nextfile}' {} + | grep -Ev "(node_modules|target)/")

# Invoking flake8 once is much faster.
flake8 --show-source --max-line-length=89 ${PYTHONFILES}
