#!/bin/sh
#
# Checks that no file contains the CR (\r) character.

FOUND_ERROR=0

# If available use ripgrep as it's faster.
if type "rg" > /dev/null; then
    MATCHES=$(rg -l '\r' meet-data/)
else
    MATCHES=$(grep -Ilr $'\r' meet-data/)
fi

# Loop over matches.
for file in $MATCHES; do
    FOUND_ERROR=1
    echo "Error: ${file} contains CRLF line endings"
done

# Fail if an error was found.
if [ "${FOUND_ERROR}" -eq 1 ]; then
    echo "Error: Some files contain CRLF line endings!"
    exit 1
fi

