#!/bin/sh

# Finds all files with a Python shebang.
#
# Reference: https://unix.stackexchange.com/questions/66097/find-all-files-with-a-python-shebang
#
# Excludes directories such as compilation targets, project dependencies, etc.,
# and file extensions which logically should not be used for Python scripts.

MATCHES=$(find . \( -path "*/node_modules" -o -path "*/target" -o -path "*/.git" \) -prune -o -type f -not -name "*.csv" -exec awk '/^#!.*python/{print FILENAME} {nextfile}' {} +)

# Invoking flake8 once with all found files is much faster than once per file.
flake8 --show-source --max-line-length=89 ${MATCHES}
