#!/usr/bin/env python3
# Checks if instagrams exist in lifter-data/social-media.csv
# Takes a while to open all these urls

import urllib.request
import sys,os
sys.path.append(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))) ,"scripts"))

import oplcsv

def enyellow(s):
    if os.name != 'nt':
        return "\033[1;33m" + s + "\033[0;m"
    else: 
        return s

def pwarning(s):
    print(' ' + enyellow(s), file=sys.stderr)

def check_ig_handle(handle, name):
    for attempt in range(4):
        try:
            ig = 'https://instagram.com/' + handle
            urllib.request.urlopen(ig)
            return True
        except urllib.error.HTTPError as e:
            if e.code == 404:
                pwarning("{0} - {1} - not found".format(name, handle))
                return False
    pwarning("{0} - {1} - could not check".format(name, handle))
    return False

def main(filename):
    csv = oplcsv.Csv(filename)
    name_index = csv.index('Name')
    ig_index = csv.index('Instagram')
    errors = 0
    total = 0
    for row in csv.rows:
        name = row[name_index]
        ig_handle = row[ig_index]
        valid = check_ig_handle(ig_handle, name)
        if (not valid):
            errors += 1
        total += 1

    print("{0} / {1} errors".format(errors, total))
    return 0

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: %s social-media.csv" % sys.argv[0])
        sys.exit(1)
    sys.exit(main(sys.argv[1]))
