#!/usr/bin/env bash
#
# Helpful script when adding meets, to just run all the tests on the CWD.
#

set -e

TESTSDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# When no arguments are passed, limit checking to just the current directory.
if [ $# -eq 0 ]; then
	CHECKER_ARGUMENTS="$( pwd )"
else
	CHECKER_ARGUMENTS=$@
fi

# Run the checker first.
(
	REPODIR="$( dirname "${TESTSDIR}" )"
	CURDIR="$( pwd )"
	cd ${REPODIR}
	cargo run --bin checker -- $CHECKER_ARGUMENTS
)

# Run the Python checks. But only if no arguments were provided.
if [ $# -eq 0 ]; then
	${TESTSDIR}/check-sex-consistency
fi
