#!/bin/sh
#
# Checks that no file contains the CR (\r) character.
#
# Note that on Windows, git will store files in the native format (CRLF),
# but will auto-convert files to the proper format (LF) based on the patterns
# in this repo's .gitattributes file.
#
# That means that running this program on Windows will report a ton of false
# positives. It's mostly useful for CI, which uses Ubuntu, and for developers
# using macOS, Linux, or another similar operating system.
#

FOUND_ERROR=0

# If available use ripgrep as it's faster.
if command -v "rg" >/dev/null 2>&1; then
    MATCHES=$(rg -l '\r' meet-data/)
else
    MATCHES=$(grep -Ilr $'\r' meet-data/)
fi

# Loop over matches.
for file in $MATCHES; do
    FOUND_ERROR=1
    echo "Error: ${file} contains CRLF line endings"
done

# Fail if an error was found.
if [ "${FOUND_ERROR}" -eq 1 ]; then
    echo "Error: Some files contain CRLF line endings!"
    exit 1
fi

