#!/usr/bin/env bash

set -x

echo "$1" > URL
cp ../../meet.template meet.csv
wget --output-document="results.pdf" "$1"
pdftotext -layout *.pdf
../reveal-negatives results.txt
cp results.txt entries.csv
