#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new meets from the THSPA.
# Results are in a database, but the front page only shows the current year.


from bs4 import BeautifulSoup
import os
import sys
import urllib.request


URLS = ["http://www.thspa.us/results_all.aspx"]
BASEURL = "http://www.thspa.us"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    urls = []
    for a in soup.find_all("a"):
        # Some links are just JS targets.
        try:
            url = a['href']
        except KeyError:
            continue

        # All the meet URLs have this parameter, luckily.
        if "passedMeetID=" not in url:
            continue

        if 'http' not in url:
            url = BASEURL + url.replace('./', '/')
        if url not in urls:
            urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    meetlist = []
    for url in URLS:
        html = gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    known = getenteredurls()

    for m in meetlist:
        if m not in known:
            print(color('[THSPA] ') + m)
    print(color('[THSPA] ') + "Continue working through archive.")


if __name__ == '__main__':
    main()
