#!/usr/bin/env python3
# Given a results.csv as outputted by rpu-parse, parse each sheet one at a time
# and join all the sheets together into an OpenPowerlifting-formatted CSV file.

import sys

sys.path.append('../../../scripts')
sys.path.append('scripts')
import oplcsv
import re


def die(s):
    print(s, file=sys.stderr)
    sys.exit(1)


# Given the array of lines, split it up into an array per-sheet.
def split_by_sheet(lines):
    # Skip past the overview.
    for i in range(len(lines)):
        if 'Sheet' in lines[i][0]:
            break
    assert i < len(lines)
    assert 'Sheet' in lines[i][0]

    sheetlist = []
    sheet = None

    for line in lines[i:]:
        # If this line starts a new sheet, generate a new array.
        if 'Sheet' in line[0]:
            sheet = []
            sheetlist.append(sheet)
        sheet.append(line)

    return sheetlist


# Find the line that contains column information (the line below does also).
def get_header_linenum(sheet):
    for ii in range(len(sheet)):
        if is_header(sheet[ii]):
            return ii

    return -1


def is_header(line):
    if '№' in ''.join(line).lower() or 'место' in ''.join(line).lower():
        return True
    return False


# Header is two merged rows, recombine these back into one row here
def fix_headers(sheet):
    headernum = get_header_linenum(sheet)
    if headernum != -1:
        header = sheet[headernum]

        linebelow = sheet[headernum + 1]

        header = [(header[ii] + " " + linebelow[ii]).strip()
                  for ii in range(0, len(header))]
        sheet[headernum - 1] = ['' for x in linebelow]

        sheet[headernum] = header

    return sheet


def parse_fieldnames(sheet):
    fieldnames = []

    headernum = get_header_linenum(sheet)
    if headernum != -1:

        header = sheet[headernum]
        # Name all the columns.
        iterable = iter(range(len(header)))

        for i in iterable:
            text = header[i].lower().replace('.', '')
            text = text.lower()

            if text == '№' or 'номер' in text:
                fieldnames.append('IGNORE')
            elif 'место' in text:
                fieldnames.append('Place')
            elif 'фамилия имя' in text:
                fieldnames.append('InternationalName')
            elif 'год родж' in text or 'год рожд' in text:
                fieldnames.append('BirthYear')
            elif 'разряд' in text or 'вып разр' in text:  # Rank
                fieldnames.append('IGNORE')
            elif 'команда / регион' in text:  # Region
                fieldnames.append('IGNORE')
            elif 'город' in text or 'субьект рф' in text:  # City
                fieldnames.append('IGNORE')
            elif 'собств вес' in text or 'соб вес' in text:
                fieldnames.append('BodyweightKg')
            elif 'ком очки' in text:
                fieldnames.append('IGNORE')
            elif 'очки по вилксу' in text:  # Wilks
                fieldnames.append('IGNORE')
            elif 'тренеры' in text:
                fieldnames.append('IGNORE')
            elif 'жре бий' in text or 'оч- ки' in text:  # Individual points
                fieldnames.append('IGNORE')
            elif text == 'дсо':  # Something to do with referees?
                fieldnames.append('IGNORE')

            elif text in ['жим 1']:
                assert header[i + 3].lower() in ['жим 2']
                assert header[i + 6].lower() in ['жим 3']
                assert header[i + 9].lower() in ['рез-т жим']
                fieldnames.append('Bench1Kg')
                fieldnames.append('IGNORE')
                fieldnames.append('IGNORE')
                fieldnames.append('Bench2Kg')
                fieldnames.append('IGNORE')
                fieldnames.append('IGNORE')
                fieldnames.append('Bench3Kg')
                fieldnames.append('IGNORE')
                fieldnames.append('IGNORE')
                fieldnames.append('BestBenchKg')
                [next(iterable) for x in range(9)]

            elif 'рез-т присед' in text or text == 'прис':
                fieldnames.append('BestSquatKg')
            elif 'рез-т жим' in text or text == 'жим':
                fieldnames.append('BestBenchKg')
            elif 'рез-т тяга' in text or text == 'тяга':
                fieldnames.append('BestDeadliftKg')

            elif 'сумма троеб' in text or text == 'сумма':
                fieldnames.append('TotalKg')

            elif text == '':  # FPR fills their spreadsheets with lots of merged blank columns
                fieldnames.append('IGNORE')

            else:
                die('Fix parse_fieldnames(): Unknown column header text: "%s"' % text)
    else:  # No header was given, use the default

        fieldnames = ['Place', 'IGNORE', 'InternationalName']
        fieldnames.extend(['IGNORE'] * 10)
        fieldnames.append('BirthYear')
        fieldnames.extend(['IGNORE'] * 26)
        fieldnames.append('BodyweightKg')
        fieldnames.extend(['IGNORE'] * 2)
        fieldnames.append('BestSquatKg')
        fieldnames.extend(['IGNORE'] * 2)
        fieldnames.append('BestBenchKg')
        fieldnames.extend(['IGNORE'] * 2)
        fieldnames.append('BestDeadliftKg')
        fieldnames.extend(['IGNORE'] * 2)
        fieldnames.append('TotalKg')

        #fieldnames = ['Place','InternationalNameName','BirthYear','IGNORE','IGNORE','IGNORE','BodyweightKg','Squat1Kg','Squat2Kg','Squat3Kg']

    return fieldnames


# Finds the division of a meet from the preamble
def get_division(sheet):
    headernum = get_header_linenum(sheet)
    division = 'Open'
    for row in sheet[0:headernum]:
        rowtext = ''.join(row).lower()
        if 'юниорок' in rowtext or 'средиюниоров' in rowtext:
            division = 'Juniors'
        elif 'юношей' in rowtext or 'девушек' in rowtext:
            division = 'Sub-Juniors'

    return division

# Search the preamble for equipment


def get_equipment(sheet):
    headernum = get_header_linenum(sheet)
    equipment = 'Single-ply'
    for row in sheet[0:headernum]:
        rowtext = ''.join(row).lower()
        if 'классическому' in rowtext:
            equipment = 'Raw'

    return equipment


# Search above the header for sex
def get_initial_sex(sheet):
    headernum = get_header_linenum(sheet)
    sex = ''
    for row in sheet[0:headernum]:
        rowtext = ''.join(row).lower()
        if 'мужчины' in rowtext:
            sex = 'M'
        elif 'женщины' in rowtext:
            sex = 'F'

    return sex


# Given a list of lines all of which belong to the same sheet, parse that
# into an OpenPowerlifting-style CSV.
def parse_sheet(sheet):
    assert 'Sheet' in sheet[0][0]
    assert sheet[0][0].count(':') == 1

    csv = oplcsv.Csv()
    title = sheet[0][0].lower()

    # FPR splits headers across multiple lines,fix this
    sheet = fix_headers(sheet)

    # Look through the sheet for column information and mark up the CSV.
    # All columns are given a name -- the extra ones are removed later.
    csv.fieldnames = parse_fieldnames(sheet)

    csv.fieldnames.append('WeightClassKg')
    csv.fieldnames.append('Event')
    csv.fieldnames.append('Equipment')
    csv.fieldnames.append('Division')
    csv.fieldnames.append('Sex')

    weightclass = None
    event = None
    equipment = get_equipment(sheet)
    division = get_division(sheet)
    sex = get_initial_sex(sheet)

    if event == None:  # Might add code to search for events in titles later
        event = ''
        if 'Squat1Kg' in csv.fieldnames or 'BestSquatKg' in csv.fieldnames:
            event += 'S'
        if 'Bench1Kg' in csv.fieldnames or 'BestBenchKg' in csv.fieldnames:
            event += 'B'
        if 'Deadlift1Kg' in csv.fieldnames or 'BestDeadliftKg' in csv.fieldnames:
            event += 'D'

    for line in sheet[get_header_linenum(sheet) + 2:]:
        text = ''.join(line)

        # Skip empty lines.
        if text == '':
            continue

        # Detect lines that set WeightClassKg state.
        if 'Весовая категория' in text:
            weightclass = ''.join(re.findall(r"\d*\.\d+|(\d+|\+)", text))
            if '+' in weightclass:  # Put the plus at the end
                weightclass = weightclass.replace('+', '') + '+'
            continue

        # Detect lines that set sex
        if 'mужчины' in text.lower():
            sex = 'M'
            continue
        elif 'женщины' in text.lower() or 'жюри' in text.lower():
            sex = 'F'
            continue

        if 'Результаты' in text:
            continue
        elif 'судейская' in text:
            continue
        elif 'Место' in text:  # Another header
            continue

        # Skip lines without a number, I think that these are always not lifter
        # data
        if line[0].strip() == '':
            continue

        if line[csv.index('InternationalName')].strip() == '':  # Skip lines without a name
            continue

        if is_header(line):
            continue

        line.append(weightclass)
        line.append(event)
        line.append(equipment)
        line.append(division)
        line.append(sex)

        if len(line) != len(csv.fieldnames):
            csv.fieldnames.extend(
                ['IGNORE'] * (len(line) - len(csv.fieldnames)))

        assert len(line) == len(csv.fieldnames)
        csv.rows.append(line)

    # Remove all the columns named 'IGNORE' before returning the CSV for
    # integration.
    while 'IGNORE' in csv.fieldnames:
        csv.remove_column_by_name('IGNORE')

    unreverse_names(csv)

    return csv


# Mark DQs properly and make sure that place is an integer.
def cleanup_place(csv):
    if 'Place' in csv.fieldnames:
        place_idx = csv.index('Place')
        div_idx = csv.index('Division')
        total_idx = csv.index('TotalKg')
        for row in csv.rows:
            if 'М1' in row[place_idx]:  # There are weird Russian M's
                row[place_idx] = row[place_idx].replace('М1', '').strip()
                row[div_idx] = 'Masters 1'
            elif 'М2' in row[place_idx]:
                row[place_idx] = row[place_idx].replace('М2', '').strip()
                row[div_idx] = 'Masters 2'
            elif 'М3' in row[place_idx]:
                row[place_idx] = row[place_idx].replace('М3', '').strip()
                row[div_idx] = 'Masters 3'
            elif 'М4' in row[place_idx]:
                row[place_idx] = row[place_idx].replace('М4', '').strip()
                row[div_idx] = 'Masters 4'

            if '.00' in row[place_idx]:  # Convert place to an integer if it wasn't already
                row[place_idx] = str(int(float(row[place_idx])))

            # Somewhat convoluted way of checking if a lifter is marked DQ and
            # has a nonzero total
            if row[place_idx] == 'DQ' and row[total_idx].replace('.', '').replace('-', '').isdigit() and float(row[total_idx]) != 0.0:
                row[place_idx] = 'DD'
                row[total_idx] = ''
            elif row[place_idx] == '' and row[total_idx].replace('.', '').replace('-', '').isdigit() and float(row[total_idx]) != 0.0:
                row[place_idx] = 'DD'
                row[total_idx] = ''
            # Everything else is a regular DQ
            elif not row[place_idx] or row[place_idx] == '-':
                row[place_idx] = 'DQ'
            elif row[place_idx] == 'дск':
                row[place_idx] = 'DQ'
            elif row[total_idx].replace('.', '').replace('-', '').isdigit() and float(row[total_idx]) == 0.0:
                row[place_idx] = 'DQ'
                row[total_idx] = ''
            elif row[total_idx] == '':
                row[place_idx] = 'DQ'


def unreverse_names(csv):

    if 'InternationalName' in csv.fieldnames:
        nameidx = csv.index('InternationalName')
    elif 'Name' in csv.fieldnames:
        nameidx = csv.index('Name')
    for row in csv.rows:
        parts = row[nameidx].split()
        if parts[-1] == 'дк':
            parts.pop()

        parts = [name.title() for name in parts]
        # The last name is probably the given first name.
        fixed = [parts[-1]] + parts[:-1]
        name = ' '.join(fixed)

        row[nameidx] = name

# Names sometimes have something in brackets after them


def cleanup_names(csv):
    if 'InternationalName' in csv.fieldnames:
        nameidx = csv.index('InternationalName')
    elif 'Name' in csv.fieldnames:
        nameidx = csv.index('Name')

    for row in csv.rows:
        row[nameidx] = re.sub('\(.*\)', '', row[nameidx])
        row[nameidx] = row[nameidx].strip()


def cleanup_lift(csv, fieldname):
    if fieldname in csv.fieldnames:
        idx = csv.index(fieldname)

        for row in csv.rows:
            amount = row[idx]

            amount = ''.join(c for c in amount if c.isdigit()
                             or c in ['.', '-'])
            amount = amount.replace('.00', '').replace('.0', '')

            if amount == 'X' or amount.replace('-', '') == '0' or not any(c.isdigit() for c in amount):
                amount = ''

            # Sometimes numbers have more than 2 commas, if so remove the
            # second one
            if len([ii for ii, a in enumerate(amount) if a == '.']) > 1:
                amount = amount[:amount.rfind(
                    '.')] + amount[amount.rfind('.') + 1:]

            row[idx] = amount


# Remove '.0' from weightclasses
def cleanup_weightclass(csv):
    if 'WeightClassKg' in csv.fieldnames:
        idx = csv.index('WeightClassKg')
        for row in csv.rows:
            if '.0' in row[idx]:
                row[idx] = row[idx].replace('.0', '')

# Sometimes weight class is also given after bodyweight


def cleanup_bodyweight(csv):
    if 'BodyweightKg' in csv.fieldnames:
        idx = csv.index('BodyweightKg')
        for row in csv.rows:
            row[idx] = row[idx].replace(
                'сн.вр.', '').replace('снята врачом', '')
            row[idx] = row[idx].replace('снят врачом', '').replace('снят', '')
            row[idx] = row[idx].replace('неявка', '')
            if row[idx] != '':
                row[idx] = row[idx].split()[0]


def assign_total(csv):

    if 'TotalKg' not in csv.fieldnames:
        csv.append_column('TotalKg')
    idx = csv.index('TotalKg')

    def weight(str):
        try:
            return float(str)
        except ValueError:
            return 0.0

    for row in csv.rows:
        if row[idx] == '':
            total = 0.0
            if 'BestSquatKg' in csv.fieldnames:
                total += weight(row[csv.index('BestSquatKg')])
            if 'BestBenchKg' in csv.fieldnames:
                total += weight(row[csv.index('BestBenchKg')])
            if 'BestDeadliftKg' in csv.fieldnames:
                total += weight(row[csv.index('BestDeadliftKg')])

            if weight(row[csv.index('BestSquatKg')]) < 0 or row[csv.index('BestSquatKg')] == '':
                total = 0.0
            elif weight(row[csv.index('BestBenchKg')]) < 0 or row[csv.index('BestBenchKg')] == '':
                total = 0.0
            elif weight(row[csv.index('BestDeadliftKg')]) < 0 or row[csv.index('BestDeadliftKg')] == '':
                total = 0.0

            if total != 0.0:
                row[idx] = str(total)


def main(filename):
    # Since the input is comma-separated, store the file as a list of lists.
    with open(filename) as fd:
        lines = [x.strip().split(',') for x in fd.readlines()]

    # Split the input filename into sheets, each of which is an independent
    # CSV.
    sheetlist = split_by_sheet(lines)

    # Parse each sheet independently, then join them all together into a
    # single CSV.
    csv = oplcsv.Csv()
    for sheet in sheetlist:
        sheetcsv = parse_sheet(sheet)
        csv.cat(sheetcsv)

    for x in ['Squat1Kg', 'Squat2Kg', 'Squat3Kg', 'Squat4Kg', 'BestSquatKg', 'Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Bench4Kg', 'BestBenchKg',
              'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg', 'Deadlift4Kg', 'BestDeadliftKg', 'TotalKg']:
        cleanup_lift(csv, x)

    assign_total(csv)

    # Now it's time to standardize the CSV a little bit!
    cleanup_place(csv)
    cleanup_names(csv)
    cleanup_weightclass(csv)
    cleanup_bodyweight(csv)

    csv.write(sys.stdout)
    return 0


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(" Usage: %s results.csv > entries.csv" % sys.argv[0])
        sys.exit(1)
    sys.exit(main(sys.argv[1]))
