#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# WRPF posts results onto a single page for now,
# but they don't post every meet (still missing Boss of Bosses 3).
#


from bs4 import BeautifulSoup
import os
import sys

sys.path.append('../../scripts')
sys.path.append('scripts')
import oplprobe


URLS = ["http://russia-powerlifting.ru/sorevnovaniya/itogovye-protokoly/2015", "http://russia-powerlifting.ru/sorevnovaniya/itogovye-protokoly/2016",
        "http://russia-powerlifting.ru/sorevnovaniya/itogovye-protokoly/protokoly-2017", "http://russia-powerlifting.ru/sorevnovaniya/itogovye-protokoly/protokoly-2018"]
BASEURL = "http://russia-powerlifting.ru/"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    content = soup.find("article", {"class": "item-page"})
    alist = content.find_all("a")

    urls = []
    for a in alist:
        link = a['href']
        # A bunch of links are just '/files/foo.xls'
        if link.startswith('/'):
            link = BASEURL + link
        urls.append(link)

    return urls


def main():

    meetlist = []
    for url in URLS:
        html = oplprobe.gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    entered = oplprobe.getenteredurls(FEDDIR)
    unentered = oplprobe.getunenteredurls(meetlist, entered)

    oplprobe.print_meets(color('[RPU]'), unentered)


if __name__ == '__main__':
    main()
