#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# WRPF posts results onto a single page for now,
# but they don't post every meet (still missing Boss of Bosses 3).
#


from bs4 import BeautifulSoup
import os
import sys

sys.path.append('../../scripts')
sys.path.append('scripts')
import oplprobe


MEETSURL = "http://wrpf.pro/protokoly/"
DOMAIN = "http://wrpf.pro"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    content = soup.find("main", {"class": "content"})
    alist = content.find_all("a")

    urls = []
    for a in alist:
        link = a['href']
        # A bunch of links are just '/files/foo.xls'
        if link.startswith('/'):
            link = DOMAIN + link
        urls.append(link)

    return urls


def main():
    html = oplprobe.gethtml(MEETSURL)
    meetlist = getmeetlist(html)

    entered = oplprobe.getenteredurls(FEDDIR)
    unentered = oplprobe.getunenteredurls(meetlist, entered)

    oplprobe.print_meets(color('[WRPF]'), unentered)


if __name__ == '__main__':
    main()
