#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# WRPF posts results onto a single page for now,
# but they don't post every meet (still missing Boss of Bosses 3).
#


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request


MEETSURL = "http://wrpf.pro/protokoly/"
DOMAIN = "http://wrpf.pro"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    content = soup.find("main", {"class": "content"});
    alist = content.find_all("a");

    urls = []
    for a in alist:
        link = a['href']
        # A bunch of links are just '/files/foo.xls'
        if link.startswith('/'):
            link = DOMAIN + link
        urls.append(link)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    html = gethtml(MEETSURL)
    meetlist = getmeetlist(html)

    known = getenteredurls()
    for m in known:
        if "%20" in m:
            known.append(m.replace("%20"," "))

    for m in meetlist:
        if not m in known:
            print(color('[WRPF] ') + m)


if __name__ == '__main__':
    main()
