// vim: set ts=4 sts=4 sw=4 et:
'use strict';

// Appease TypeScript compiler.
declare let opldb;
declare let meetdb;


// Interface declarations for the opldb and meetdb.
// TODO: This should be auto-generated by the script that compiles the database.
export const enum OplDBColumn {
    MeetID,
    Name,
    Sex,
    Equipment,
    Age,
    Division,
    BodyweightKg,
    WeightClassKg,
    Squat4Kg,
    BestSquatKg,
    Bench4Kg,
    BestBenchKg,
    Deadlift4Kg,
    BestDeadliftKg,
    TotalKg,
    Place,
    Wilks,
}

export const enum MeetDBColumn {
    MeetID,
    MeetPath,
    Federation,
    Date,
    MeetCountry,
    MeetState,
    MeetTown,
    MeetName,
}


export function db_make_indices_list(): number[] {
    let indices = Array(opldb.data.length);
    for (let i = 0; i < opldb.data.length; ++i) {
        indices[i] = i;
    }
    return indices;
}


export function db_filter(indices: number[], rowcmpfn): number[] {
    return indices.filter(function (e) {
        let row = opldb.data[e];
        return rowcmpfn(row);
    });
}


export function db_sort_numeric_minfirst(indices: number[], colidx): number[] {
    indices.sort(function (a, b) {
        let av = Number(opldb.data[a][colidx]);
        let bv = Number(opldb.data[b][colidx]);
        if (isNaN(av))
            av = Number.MAX_VALUE;
        if (isNaN(bv))
            bv = Number.MAX_VALUE;
        return av - bv;
    });
    return indices;
}


export function db_sort_numeric_maxfirst(indices: number[], colidx): number[] {
    indices.sort(function (a, b) {
        let av = Number(opldb.data[a][colidx]);
        let bv = Number(opldb.data[b][colidx]);
        if (isNaN(av))
            av = Number.MIN_VALUE;
        if (isNaN(bv))
            bv = Number.MIN_VALUE;
        return bv - av;
    });
    return indices;
}


// Keep only the first occurrence of NAME. The indices list should already be sorted.
export function db_uniq_lifter(indices: number[]): number[] {
    let seen = {};

    return indices.filter(function (e) {
        let name = opldb.data[e][OplDBColumn.Name];
        if (seen[name])
            return false;
        seen[name] = true;
        return true;
    });
}


// Look up a meet by information.
// MeetID is not suitable for URLs since it may change on recompilation.
export function db_get_meetid(fed: string, date: string, meetname: string): number {
    for (let i = 0; i < meetdb.data.length; ++i) {
        let row = meetdb.data[i];
        if (row[MeetDBColumn.Federation] === fed &&
            row[MeetDBColumn.Date] === date &&
            row[MeetDBColumn.MeetName] === meetname)
        {
            return i;
        }
    }
    return -1;
}


// Look up a meet by meetpath.
export function db_get_meetid_by_meetpath(meetpath: string): number {
    for (let i = 0; i < meetdb.data.length; ++i) {
        let row = meetdb.data[i];
        if (row[MeetDBColumn.MeetPath] === meetpath) {
            return i;
        }
    }
    return -1;
}
