---
- name: ensure webservers updated and running
  hosts: webservers
  roles:
    - nginx
    - openpl-app
    - goaccess
    # - sysupdate  # Disabled temporarily: DigitalOcean's do-agent doesn't work on Fedora 43.
