[divisions]
    open = {name ="Open",min=0,max=999}
    specialolympics = {name ="Special Olympics",min=0,max=999}


    m4049 = {name ="40-49",min=40,max=49}
    m5059 = {name ="50-59",min=50,max=59}
    m6069 = {name ="60-69",min=60,max=69}
    m7079 = {name ="70-79",min=70,max=79}
    m80 = {name ="80-89",min=80,max=89} #Masters 5
    s3339 = {name ="33-39",min=33,max=39}
    t1319 = {name ="13-19",min=13,max=19}
    j2023 = {name ="20-23",min=19.5,max=23}



[weightclasses.default_M]
    classes = ["39","44","48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"


[weightclasses.default_F]
    classes = ["39","44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
    1801 = ["ExemptWeightClassConsistency"] # Lifters with no BW or WC.
    2501 = ["ExemptDivision"]
