# Configuration for THSPA.

[options]
    valid_federations = ["NMAA"]

[divisions]
    # The main division used for almost everything.
    boys = {name="Boys", min=13, max=19, sex="M"}
    girls = {name="Girls", min=13, max=19, sex="F"}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","117.5","117.5+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"


[exemptions]
    7414 = ["ExemptWeightClassConsistency"]
    7415 = ["ExemptWeightClassConsistency"]
    7416 = ["ExemptWeightClassConsistency"]
    7417 = ["ExemptWeightClassConsistency"]
    7418 = ["ExemptWeightClassConsistency"]
    7419 = ["ExemptWeightClassConsistency"]
    7421 = ["ExemptWeightClassConsistency"]
    7423 = ["ExemptWeightClassConsistency"]
    7426 = ["ExemptWeightClassConsistency"]
    7428 = ["ExemptWeightClassConsistency"]
    7432 = ["ExemptWeightClassConsistency"]
    7433 = ["ExemptWeightClassConsistency"]
    7434 = ["ExemptWeightClassConsistency"]
    7435 = ["ExemptWeightClassConsistency"]
    7436 = ["ExemptWeightClassConsistency"]
    7438 = ["ExemptWeightClassConsistency"]
    7439 = ["ExemptWeightClassConsistency"]
    7440 = ["ExemptWeightClassConsistency"]
    7441 = ["ExemptWeightClassConsistency"]
    7443 = ["ExemptWeightClassConsistency"]
    7444 = ["ExemptWeightClassConsistency"]
    7446 = ["ExemptWeightClassConsistency"]
    7448 = ["ExemptWeightClassConsistency"]
    7450 = ["ExemptWeightClassConsistency"]
    7452 = ["ExemptWeightClassConsistency"]
    7454 = ["ExemptWeightClassConsistency"]
    7455 = ["ExemptWeightClassConsistency"]
    7457 = ["ExemptWeightClassConsistency"]
    7459 = ["ExemptWeightClassConsistency"]
    7460 = ["ExemptWeightClassConsistency"]
    7463 = ["ExemptWeightClassConsistency"]
    7464 = ["ExemptWeightClassConsistency"]
    7467 = ["ExemptWeightClassConsistency"]
    7469 = ["ExemptWeightClassConsistency"]
    7470 = ["ExemptWeightClassConsistency"]
    7413 = ["ExemptWeightClassConsistency"]
	