# Configuration for THSPA.

[options]
    valid_federations = ["NMAA"]

[divisions]
    # The main division used for almost everything.
    boys = {name="Boys", min=13, max=19, sex="M"}
    girls = {name="Girls", min=13, max=19, sex="F"}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","117.5","117.5+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"


[exemptions]
