# Configuration for NMAA.

[options]
    valid_federations = ["NMAA"]

[divisions]
    # The main division used for almost everything.
    boys = {name="Boys", min=13, max=19, sex="M"}
    girls = {name="Girls", min=13, max=19, sex="F"}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","117.5","117.5+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"


[exemptions]
    7414 = ["ExemptWeightClassConsistency"]
    7415 = ["ExemptWeightClassConsistency"]
    7416 = ["ExemptWeightClassConsistency"]
    7417 = ["ExemptWeightClassConsistency"]
    7418 = ["ExemptWeightClassConsistency"]
    7419 = ["ExemptWeightClassConsistency"]
    7421 = ["ExemptWeightClassConsistency"]
    7423 = ["ExemptWeightClassConsistency"]
    7426 = ["ExemptWeightClassConsistency"]
    7428 = ["ExemptWeightClassConsistency"]
    7432 = ["ExemptWeightClassConsistency"]
    7433 = ["ExemptWeightClassConsistency"]
    7434 = ["ExemptWeightClassConsistency"]
    7435 = ["ExemptWeightClassConsistency"]
    7436 = ["ExemptWeightClassConsistency"]
    7438 = ["ExemptWeightClassConsistency"]
    7439 = ["ExemptWeightClassConsistency"]
    7440 = ["ExemptWeightClassConsistency"]
    7441 = ["ExemptWeightClassConsistency"]
    7443 = ["ExemptWeightClassConsistency"]
    7444 = ["ExemptWeightClassConsistency"]
    7446 = ["ExemptWeightClassConsistency"]
    7448 = ["ExemptWeightClassConsistency"]
    7450 = ["ExemptWeightClassConsistency"]
    7452 = ["ExemptWeightClassConsistency"]
    7454 = ["ExemptWeightClassConsistency"]
    7455 = ["ExemptWeightClassConsistency"]
    7457 = ["ExemptWeightClassConsistency"]
    7459 = ["ExemptWeightClassConsistency"]
    7460 = ["ExemptWeightClassConsistency"]
    7463 = ["ExemptWeightClassConsistency"]
    7464 = ["ExemptWeightClassConsistency"]
    7467 = ["ExemptWeightClassConsistency"]
    7469 = ["ExemptWeightClassConsistency"]
    7470 = ["ExemptWeightClassConsistency"]
    7413 = ["ExemptWeightClassConsistency"]
    7473 = ["ExemptWeightClassConsistency"]
    7474 = ["ExemptWeightClassConsistency"]
    7305 = ["ExemptWeightClassConsistency"]
    7309 = ["ExemptWeightClassConsistency"]
    7310 = ["ExemptWeightClassConsistency"]
    7311 = ["ExemptWeightClassConsistency"]
    7312 = ["ExemptWeightClassConsistency"]
    7317 = ["ExemptWeightClassConsistency"]
    7318 = ["ExemptWeightClassConsistency"]
    7319 = ["ExemptWeightClassConsistency"]
    7320 = ["ExemptWeightClassConsistency"]
    7322 = ["ExemptWeightClassConsistency"]
    7323 = ["ExemptWeightClassConsistency"]
    7324 = ["ExemptWeightClassConsistency"]
    7325 = ["ExemptWeightClassConsistency"]
    7326 = ["ExemptWeightClassConsistency"]
    7327 = ["ExemptWeightClassConsistency"]
    7330 = ["ExemptWeightClassConsistency"]
    7333 = ["ExemptWeightClassConsistency"]
    7334 = ["ExemptWeightClassConsistency"]
    7335 = ["ExemptWeightClassConsistency"]
    7337 = ["ExemptWeightClassConsistency"]
    7338 = ["ExemptWeightClassConsistency"]
    7339 = ["ExemptWeightClassConsistency"]
    7340 = ["ExemptWeightClassConsistency"]
    7341 = ["ExemptWeightClassConsistency"]
    7342 = ["ExemptWeightClassConsistency"]
    7344 = ["ExemptWeightClassConsistency"]
    7345 = ["ExemptWeightClassConsistency"]
    7346 = ["ExemptWeightClassConsistency"]
    7347 = ["ExemptWeightClassConsistency"]
    7348 = ["ExemptWeightClassConsistency"]
    7349 = ["ExemptWeightClassConsistency"]
    7351 = ["ExemptWeightClassConsistency"]
    7352 = ["ExemptWeightClassConsistency"]
    7354 = ["ExemptWeightClassConsistency"]
    7355 = ["ExemptWeightClassConsistency"]
    7356 = ["ExemptWeightClassConsistency"]
    7357 = ["ExemptWeightClassConsistency"]
    7358 = ["ExemptWeightClassConsistency"]
    7359 = ["ExemptWeightClassConsistency"]
    7360 = ["ExemptWeightClassConsistency"]
    7362 = ["ExemptWeightClassConsistency"]
    7363 = ["ExemptWeightClassConsistency"]
    7364 = ["ExemptWeightClassConsistency"]
    7365 = ["ExemptWeightClassConsistency"]
    7367 = ["ExemptWeightClassConsistency"]
    7368 = ["ExemptWeightClassConsistency"]
    7369 = ["ExemptWeightClassConsistency"]
    7371 = ["ExemptWeightClassConsistency"]
    7372 = ["ExemptWeightClassConsistency"]
    7374 = ["ExemptWeightClassConsistency"]
    7375 = ["ExemptWeightClassConsistency"]
    7377 = ["ExemptWeightClassConsistency"]
    7378 = ["ExemptWeightClassConsistency"]
    7379 = ["ExemptWeightClassConsistency"]
    7381 = ["ExemptWeightClassConsistency"]
    7382 = ["ExemptWeightClassConsistency"]
    7383 = ["ExemptWeightClassConsistency"]
    7385 = ["ExemptWeightClassConsistency"]
    7389 = ["ExemptWeightClassConsistency"]
    7390 = ["ExemptWeightClassConsistency"]
    7391 = ["ExemptWeightClassConsistency"]
    7392 = ["ExemptWeightClassConsistency"]
    7394 = ["ExemptWeightClassConsistency"]
    7395 = ["ExemptWeightClassConsistency"]
    7396 = ["ExemptWeightClassConsistency"]
    7398 = ["ExemptWeightClassConsistency"]
    7399 = ["ExemptWeightClassConsistency"]
    7402 = ["ExemptWeightClassConsistency"]
    7405 = ["ExemptWeightClassConsistency"]
    7410 = ["ExemptWeightClassConsistency"]
    7307 = ["ExemptWeightClassConsistency"]
    7308 = ["ExemptWeightClassConsistency"]
    7370 = ["ExemptWeightClassConsistency"]
    7387 = ["ExemptWeightClassConsistency"]
    7321 = ["ExemptWeightClassConsistency"]
    7388 = ["ExemptWeightClassConsistency"]
    7393 = ["ExemptWeightClassConsistency"]
    7411 = ["ExemptWeightClassConsistency"]
	7412 = ["ExemptWeightClassConsistency"]
	7477 = ["ExemptWeightClassConsistency"]
	7478 = ["ExemptWeightClassConsistency"]
    7192 = ["ExemptWeightClassConsistency"]
    7194 = ["ExemptWeightClassConsistency"]
    7195 = ["ExemptWeightClassConsistency"]
    7197 = ["ExemptWeightClassConsistency"]
    7198 = ["ExemptWeightClassConsistency"]
    7200 = ["ExemptWeightClassConsistency"]
    7201 = ["ExemptWeightClassConsistency"]
    7204 = ["ExemptWeightClassConsistency"]
    7205 = ["ExemptWeightClassConsistency"]
    7206 = ["ExemptWeightClassConsistency"]
    7207 = ["ExemptWeightClassConsistency"]
    7208 = ["ExemptWeightClassConsistency"]
    7210 = ["ExemptWeightClassConsistency"]
    7211 = ["ExemptWeightClassConsistency"]
    7212 = ["ExemptWeightClassConsistency"]
    7213 = ["ExemptWeightClassConsistency"]
    7217 = ["ExemptWeightClassConsistency"]
    7219 = ["ExemptWeightClassConsistency"]
    7222 = ["ExemptWeightClassConsistency"]
    7223 = ["ExemptWeightClassConsistency"]
    7225 = ["ExemptWeightClassConsistency"]
    7227 = ["ExemptWeightClassConsistency"]
    7228 = ["ExemptWeightClassConsistency"]
    7229 = ["ExemptWeightClassConsistency"]
    7234 = ["ExemptWeightClassConsistency"]
    7236 = ["ExemptWeightClassConsistency"]
    7238 = ["ExemptWeightClassConsistency"]
    7239 = ["ExemptWeightClassConsistency"]
    7242 = ["ExemptWeightClassConsistency"]
    7248 = ["ExemptWeightClassConsistency"]
    7249 = ["ExemptWeightClassConsistency"]
    7251 = ["ExemptWeightClassConsistency"]
    7252 = ["ExemptWeightClassConsistency"]
    7253 = ["ExemptWeightClassConsistency"]
    7256 = ["ExemptWeightClassConsistency"]
    7257 = ["ExemptWeightClassConsistency"]
    7260 = ["ExemptWeightClassConsistency"]
    7263 = ["ExemptWeightClassConsistency"]
    7264 = ["ExemptWeightClassConsistency"]
    7266 = ["ExemptWeightClassConsistency"]
    7267 = ["ExemptWeightClassConsistency"]
    7270 = ["ExemptWeightClassConsistency"]
    7274 = ["ExemptWeightClassConsistency"]
    7275 = ["ExemptWeightClassConsistency"]
    7276 = ["ExemptWeightClassConsistency"]
    7277 = ["ExemptWeightClassConsistency"]
    7278 = ["ExemptWeightClassConsistency"]
    7279 = ["ExemptWeightClassConsistency"]
    7280 = ["ExemptWeightClassConsistency"]
    7282 = ["ExemptWeightClassConsistency"]
    7284 = ["ExemptWeightClassConsistency"]
    7286 = ["ExemptWeightClassConsistency"]
    7288 = ["ExemptWeightClassConsistency"]
    7290 = ["ExemptWeightClassConsistency"]
    7291 = ["ExemptWeightClassConsistency"]
    7292 = ["ExemptWeightClassConsistency"]
    7293 = ["ExemptWeightClassConsistency"]
    7294 = ["ExemptWeightClassConsistency"]
    7298 = ["ExemptWeightClassConsistency"]
    7299 = ["ExemptWeightClassConsistency"]
    7303 = ["ExemptWeightClassConsistency"]
    7271 = ["ExemptWeightClassConsistency"]
    7220 = ["ExemptWeightClassConsistency"]
    7240 = ["ExemptWeightClassConsistency"]
    7243 = ["ExemptWeightClassConsistency"]
    7244 = ["ExemptWeightClassConsistency"]
    7269 = ["ExemptWeightClassConsistency"]
    7285 = ["ExemptWeightClassConsistency"]
    7297 = ["ExemptWeightClassConsistency"]
    7301 = ["ExemptWeightClassConsistency"]
    7302 = ["ExemptWeightClassConsistency"]
	7479 = ["ExemptWeightClassConsistency"]
