#!/bin/bash

set -e

if [ $# -ne 1 ]; then
	echo " Usage: $0 http://url/to/results/page"
	exit 1
fi

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

# Download the website to original.html.
wget --output-document=original.html "$1"

# Save the website URL for future use, since it's pretty hard to tell
# what meets on the site are tracked and which aren't.
echo "$1" > URL

# Sometimes the documents are encoded in ISO-8859-1.
file original.html | grep Non-ISO && iconv -f  ISO-8859-1 -t UTF-8 original.html > original2.html
if [ -f original2.html ]; then
    mv original2.html original.html
fi

mv original.html original.xls

# Use LibreOffice to automatically convert the <table> to a csv file.
# This creates original.csv.
libreoffice --headless --convert-to csv original.xls

# If CSV conversion completed successfully, remove the intermediary
# files early to benefit terminal autocompletion.
if [ -f original.csv ]; then
        rm original.xls
fi

cp "${SCRIPTDIR}/../meet.template" "meet.csv"
