#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for meet results from the 100%RAW Federation (RAW).
# RAW posts meets to a page separated by year.


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request

FEDDIR = os.path.dirname(os.path.realpath(__file__))
YEAR = datetime.datetime.now().strftime("%Y")
URL = "http://www.apa-wpa.com/APA/?page_id=1763"
BASEURL = "http://www.apa-wpa.com/APA/?page_id=1763"


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;30m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')
    entry_content = soup.find("div", {"class": "entry-content"})

    urls = []
    for a in entry_content.find_all('a'):
        url = a['href']
        if not 'http://' in url:
            url = BASEURL + url

        if not url in urls:
            urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    meetlist = []

    html = gethtml(URL)
    meetlist = getmeetlist(html)

    known = getenteredurls()

    for m in meetlist:
        if not m in known:
            print(color('[APA] ') + m)
    print(color('[APA] ') + "Continue working through archive.")

if __name__ == '__main__':
    main()
