#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new meets from the FESUPO, hosted by Powerlifting Argentina.
#


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request

sys.path.append('../../scripts')
sys.path.append('scripts')
import oplprobe


URLS = ["http://www.powerlifting.com.ar/fesupo%20resultados.htm"]
BASEURL = "http://www.powerlifting.com.ar/"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;33m" + s + "\033[0;m"

def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    urls = []
    for a in soup.find_all('a'):
        url = a['href']

        if not 'http' in url:
            url = BASEURL + url
            url = url.replace('.com//','/')
        if not url in urls:
            urls.append(url)

    return urls

def main():
    meetlist = []
    for url in URLS:
        html = oplprobe.gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    entered = oplprobe.getenteredurls(FEDDIR)
    unentered = oplprobe.getunenteredurls(meetlist, entered)

    oplprobe.print_meets(color('[FESUPO]'), unentered)



if __name__ == '__main__':
    main()
