#!/usr/bin/env bash
# A simple script that reports social media information to our Zulip teamchat.

SCRIPTDIR=`dirname "$0"`

# Require authentication variables.
if [ -z "${ZULIP_SOCIALBOT_EMAIL}" ]; then
        echo " Error: ${0} requires ZULIP_SOCIALBOT_EMAIL in ~/.bash_profile."
        echo " The value can be found on the Settings / Your Bots page in Zulip."
        exit 1
fi
if [ -z "${ZULIP_SOCIALBOT_API_KEY}" ]; then
        echo " Error: ${0} requires ZULIP_SOCIALBOT_API_KEY in ~/.bash_profile."
        echo " The value can be found on the Settings / Your Bots page in Zulip."
        exit 1
fi

# Sends the message in "$2" to Zulip chat with subject "$1".
function send_message {
        curl https://openpl.zulipchat.com/api/v1/messages \
                -u "${ZULIP_SOCIALBOT_EMAIL}:${ZULIP_SOCIALBOT_API_KEY}" \
                -d "type=stream" \
                -d "to=social media" \
                --data-urlencode "subject=${1}" \
                --data-urlencode "content=${2}"
}

# Posts follower counts to the Zulip chat for the IG account in "$1".
function post_for {
	INSTAGRAM_MESSAGE=$(python3 "${SCRIPTDIR}/parse-instagram.py" "$1")
	if [[ ! -z "$INSTAGRAM_MESSAGE" ]]; then
		send_message "Instagram Stats" "$INSTAGRAM_MESSAGE"
	fi
}

# Post all our accounts into chat.
post_for "openpowerlifting"
post_for "openipf"
post_for "openpupperlifting"
