#!/bin/bash
#

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

# Use IPF-specific knowledge to parse results.csv into lifters.csv.
${SCRIPTDIR}/ipf-standardize-csv results.csv > lifters.csv

# Show any warnings.
${REPOSCRIPTDIR}/check-lifters-csv lifters.csv

# Copy the template to the current directory for filling in.
cp ${SCRIPTDIR}/../meet.template meet.csv

echo "Done! Don't forget about meet.csv!"
