#!/bin/bash
#

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"
REPOTESTDIR="${SCRIPTDIR}/../../tests"

# Use IPF-specific knowledge to parse results.csv into entries.csv.
${SCRIPTDIR}/ipf-standardize-csv results.csv > entries.csv

# Show any warnings.
${REPOTESTDIR}/check-entries-csv entries.csv

# Copy the template to the current directory for filling in.
cp ${SCRIPTDIR}/../meet.template meet.csv

echo "Done! Don't forget about meet.csv!"
