#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new meets from Powerlifting Australia.
# What a nice federation! Results are already in tables!


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request


URLS = ["https://powerliftingaustralia.com/results/",
        "https://powerliftingaustralia.com/results/2008-results/"]
BASEURL = "https://powerliftingaustralia.com"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;36m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    content = soup.find_all("div", {"class": "post-content"})
    if len(content) == 0:
        error("Page layout seems to have changed.")
    elif len(content) > 1:
        error("Multiple result areas found.")

    urls = []
    for a in content[0].find_all('a'):
        url = a['href']
        if not 'http' in url:
            url = BASEURL + url
        if not url in urls:
            urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    meetlist = []
    for url in URLS:
        html = gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    known = getenteredurls()

    for m in meetlist:
        if not m in known:
            print(color('[PA] ') + m)
    print(color('[PA] ') + "Continue working through archive.")


if __name__ == '__main__':
    main()
