#!/bin/bash
#
# Often it happens that pa-standardize-csv fails, and
# results.csv must be hand-edited to get it to a reasonable format.
#
# This file contains the commands that would be executed at the end
# of pa-parse, that I have to execute by hand in case things go wrong,
# to save me some repetitive typing.
#

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"
REPOTESTDIR="${SCRIPTDIR}/../../tests"

# Use PA-specific knowledge to parse results.csv into entries.csv.
${SCRIPTDIR}/pa-standardize-csv results.csv > entries.csv

# Transform ",200.0," -> ",200,".
sed -i -e "s/,\([0-9][0-9]*\)\.0,/,\1,/g" entries.csv
sed -i -e "s/,\(-[0-9][0-9]*\)\.0,/,\1,/g" entries.csv

# Copy the template to the current directory for filling in.
cp ${SCRIPTDIR}/../meet.template meet.csv

echo PA >> meet.csv

# Calculate place for 2013 and earlier documents that don't self-report.
${REPOSCRIPTDIR}/calc-place entries.csv || true

# Show any warnings.
${REPOTESTDIR}/check-entries-csv entries.csv

echo "Done! Don't forget about meet.csv!"
