#!/bin/bash
# Extract a lifters.csv file from a meet result.txt file.
# The output file still needs to be manually edited and audited;
#  the goal is to get the data into a pretty-close state so editing is quick.

if [ $# -lt 1 ]; then
    echo " Usage: ${0} results.txt"
    exit 1
fi

# Always output the format header, which will be deleted during editing.
cat ~/dev/openpowerlifting/meet-data/lifters-header

# Convert the txt file to a csv, by replacing all instances of at least two spaces with a comma.
# Also gets rid of "-------", which is sometimes used to indicate complete failure without
#  providing any meaningful data.
# Also takes out some characters that we won't need, which represent record-setting lifts.
sed 's/ \{2,\}/,/g' "${1}" | sed 's/-\{2,\}//g' \
  | sed 's/!//g' | sed 's/\*//g' | sed 's/#//g' | sed 's/\$//g' | ~/dev/openpowerlifting/meet-data/track-csv-state
