# Configuration for Strength Sports Australia, formerly the APU

[options]
require_manual_disambiguation = true

[divisions]
# WDFPF-specific divisions 2024 onwards, from the WDFPF rulebook located at https://wdfpf.co.uk/
open = { name = "Open", min = 0, max = 999 }
t1 = { name = "Teenage 1", min = 14, max = 15 }
t2 = { name = "Teenage 2", min = 16, max = 17 }
t3 = { name = "Teenage 3", min = 18, max = 19 }
jr = { name = "Junior", min = 20, max = 23 }
m1 = { name = "Masters 1", min = 40, max = 44 }
m2 = { name = "Masters 2", min = 45, max = 49 }
m3 = { name = "Masters 3", min = 50, max = 54 }
m4 = { name = "Masters 4", min = 55, max = 59 }
m5 = { name = "Masters 5", min = 60, max = 64 }
m6 = { name = "Masters 6", min = 65, max = 69 }
m7 = { name = "Masters 7", min = 70, max = 74 }
m8 = { name = "Masters 8", min = 75, max = 79 }
m9 = { name = "Masters 9", min = 80, max = 84 }
m10 = { name = "Masters 10", min = 85, max = 89 }
m11 = { name = "Masters 11", min = 90, max = 94 }
m12 = { name = "Masters 12", min = 95, max = 99 }

# USAPL-style divisions, 2021-2023.
mro = { name = "MR-O", min = 14, max = 999, sex = "M", equipment = "Raw" }
mry = { name = "MR-Y", min = 8, max = 13, sex = "M", equipment = "Raw" }
mrsj = { name = "MR-SJ", min = 0, max = 17.5, sex = "M", equipment = "Raw" }
mrjr = { name = "MR-Jr", min = 0, max = 22.5, sex = "M", equipment = "Raw" }
mrm = { name = "MR-M", min = 39.5, max = 999, sex = "M", equipment = "Raw" }
mrm1 = { name = "MR-M1", min = 39.5, max = 48.5, sex = "M", equipment = "Raw" }
mrm2 = { name = "MR-M2", min = 49.5, max = 58.5, sex = "M", equipment = "Raw" }
mrm3 = { name = "MR-M3", min = 59.5, max = 68.5, sex = "M", equipment = "Raw" }
mrm4 = { name = "MR-M4", min = 69.5, max = 999, sex = "M", equipment = "Raw" }
mrg = { name = "MR-G", min = 0, max = 999, sex = "M", equipment = "Raw", place = "G" }

fro = { name = "FR-O", min = 14, max = 999, sex = "F", equipment = "Raw" }
fry = { name = "FR-Y", min = 8, max = 13, sex = "F", equipment = "Raw" }
frsj = { name = "FR-SJ", min = 0, max = 17.5, sex = "F", equipment = "Raw" }
frjr = { name = "FR-Jr", min = 0, max = 22.5, sex = "F", equipment = "Raw" }
frm = { name = "FR-M", min = 39.5, max = 999, sex = "F", equipment = "Raw" }
frm1 = { name = "FR-M1", min = 39.5, max = 48.5, sex = "F", equipment = "Raw" }
frm2 = { name = "FR-M2", min = 49.5, max = 58.5, sex = "F", equipment = "Raw" }
frm3 = { name = "FR-M3", min = 59.5, max = 68.5, sex = "F", equipment = "Raw" }
frm4 = { name = "FR-M4", min = 69.5, max = 999, sex = "F", equipment = "Raw" }
frg = { name = "FR-G", min = 0, max = 999, sex = "F", equipment = "Raw", place = "G" }

mo = { name = "M-O", sex = "M", min = 0, max = 999, equipment = "Single-ply" }
msjr = { name = "M-SJ", sex = "M", min = 0, max = 17.5, equipment = "Single-ply" }
mjr = { name = "M-Jr", sex = "M", min = 0, max = 22.5, equipment = "Single-ply" }
mm1 = { name = "M-M1", sex = "M", min = 39.5, max = 48.5, equipment = "Single-ply" }
mm2 = { name = "M-M2", sex = "M", min = 49.5, max = 58.5, equipment = "Single-ply" }
mm3 = { name = "M-M3", sex = "M", min = 59.5, max = 68.5, equipment = "Single-ply" }
mm4 = { name = "M-M4", sex = "M", min = 69.5, max = 78.5, equipment = "Single-ply" }

fo = { name = "F-O", sex = "F", min = 0, max = 999, equipment = "Single-ply" }
fsjr = { name = "F-SJ", sex = "F", min = 0, max = 17.5, equipment = "Single-ply" }
fjr = { name = "F-Jr", sex = "F", min = 0, max = 22.5, equipment = "Single-ply" }
fm1 = { name = "F-M1", sex = "F", min = 39.5, max = 48.5, equipment = "Single-ply" }
fm2 = { name = "F-M2", sex = "F", min = 49.5, max = 58.5, equipment = "Single-ply" }
fm3 = { name = "F-M3", sex = "F", min = 59.5, max = 68.5, equipment = "Single-ply" }
fm4 = { name = "F-M4", sex = "F", min = 69.5, max = 78.5, equipment = "Single-ply" }

# WDFPF weightclasses have changed to include 110, 110+
[weightclasses.new_F]
classes = [
    "44",
    "47.5",
    "50.5",
    "53",
    "55.5",
    "58.5",
    "63",
    "70",
    "80",
    "90",
    "110",
    "110+",
]
date_range = ["2024-11-01", "9999-01-01"]
sex = "F"

# WDFPF weightclasses, 2024 onwards.
[weightclasses.default_M]
classes = [
    "52",
    "56",
    "60",
    "67.5",
    "75",
    "82.5",
    "90",
    "100",
    "110",
    "125",
    "145",
    "145+",
]
date_range = ["2024-01-01", "9999-01-01"]
sex = "M"

[weightclasses.default_F]
classes = [
    "44",
    "47.5",
    "50.5",
    "53",
    "55.5",
    "58.5",
    "63",
    "70",
    "80",
    "90",
    "90+",
]
date_range = ["2024-01-01", "2024-10-31"]
sex = "F"

[exemptions]
