# Configuration for WPC-Italy.

[options]
    require_manual_disambiguation = true

[divisions]
    # Currently unconfigured.

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2014-12-31"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2014-12-31"]
    sex = "F"

[exemptions]
    1601 = ["ExemptLiftOrder"] # Allowed lowering 4th attempts.
