#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes the English version of the Super Cup of Titans page
# for new results. They seem to be posted at the same time
# as on the Russian page, so it may be unnecessary to check both.


from bs4 import BeautifulSoup
import os
import sys
import urllib.request


SCTDIR = os.path.dirname(os.path.realpath(__file__))
SCTURL = "http://supercupoftitans.ru/tournaments-eng.html"
BASEURL = "http://supercupoftitans.ru"


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    menu = soup.find("div", {"class": "menuRight"})
    if len(menu) == 0:
        error("Couldn't find the right menu.")

    urls = []
    for a in menu.find_all('a'):
        url = a['href']
        # They use relative URLs a lot. Expand to the full path.
        if 'http' not in url:
            url = BASEURL + '/' + url

        if url not in urls:
            urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(SCTDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    html = gethtml(SCTURL)
    meets = getmeetlist(html)

    known = getenteredurls()

    for m in meets:
        if m not in known:
            print(color('[SCT] ') + m)


if __name__ == '__main__':
    main()
