#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new APF/AAPF/WPC meets.
# Also checks the results archive.


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request


URLS = ["http://worldpowerliftingcongress.com/wpc-results/"]
#        "http://worldpowerliftingcongress.com/results-archive/"]
# TODO: Re-enable the archive once the current results have been worked through.

BASEURL = "http://worldpowerliftingcongress.com"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;37m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    main = soup.find("div", {"id": "main-content"})
    divs = main.find_all("div", {"class": "wpb_wrapper"})
    if len(divs) == 0:
        error("Page layout seems to have changed.")

    urls = []

    for div in divs:
        for a in div.find_all('a'):
            url = a['href']
            if not 'http' in url:
                url = BASEURL + '/' + url

            # Remove some false positives.
            if '/#' in url:
                continue

            if not url in urls:
                urls.append(url.strip())

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    quick = False
    if '--quick' in sys.argv:
        quick = True

    meetlist = []
    for url in URLS:
        html = gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    known = getenteredurls()

    count = 0
    for m in meetlist:
        if not m in known:
            count += 1
            if not quick or count <= 6:
                print(color('[APF] ') + m)

    if count > 0:
        print(color('[APF] ') + '%d meets remaining.' % count)

    print(color('[APF] ') + "Continue working through archive.")


if __name__ == '__main__':
    main()
