#!/bin/bash
#
# Often it happens that rps-standardize-csv fails, and
# original.csv must be hand-edited to get it to a reasonable format.
#
# This file contains the commands that would be executed at the end
# of rps-parse, that I have to execute by hand in case things go wrong,
# to save me some repetitive typing.
#

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"
REPOTESTSDIR="${SCRIPTDIR}/../../tests"

# Use RPS-specific knowledge to parse original.csv into entries.csv.
${SCRIPTDIR}/rps-standardize-csv.py original.csv > entries.csv

# Convert to kg.
${REPOSCRIPTDIR}/csv-tokg entries.csv
${REPOSCRIPTDIR}/fix-weightclasses entries.csv

# Copy the template to the current directory for filling in.
cp ${SCRIPTDIR}/../meet.template meet.csv
echo "RPS,,USA,,," >> meet.csv

# Show any warnings.
${REPOTESTSDIR}/check

echo "Done! Don't forget about meet.csv!"
