#!/bin/bash

set -e


if [ $# -ne 2 ]; then
	echo " Usage: $0 dirname http://url/to/results/page"
	exit 1
fi

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

mkdir "$1"
cd "$1"




# Download the website to original.html.
wget --output-document=original.html "$2"

# Save the website URL for future use, since it's pretty hard to tell
# what meets on the site are tracked and which aren't.
echo "$2" > URL

# Extract just the original table from original.html.
# Save it as original.xls so that libreoffice can convert to csv.
${SCRIPTDIR}/rps-extract-table.py original.html > original.xls

# Remove any commas in the xls file.
sed -i -e 's/,//g' original.xls

# Use LibreOffice to automatically convert the <table> to a csv file.
# This creates original.csv.
LANG=C libreoffice --headless --convert-to csv original.xls

# Remove NBSP
sed -i -e 's/\xa0//g' original.csv

# If CSV conversion completed successfully, remove the intermediary
# files early to benefit terminal autocompletion.
if [ -f original.csv ]; then
	rm original.html original.xls
fi

# Commands after this point were extracted into a separate file
# since they had to be re-run by hand in case of error.
${SCRIPTDIR}/rps-import-post
