#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Standardize the results.csv to the OpenPowerlifting
# internal format.
#

import sys
from oplcsv import Csv


def error(msg):
    print("Error: %s" % msg, file=sys.stderr)
    sys.exit(1)


def strip_whitespace(csv):
    for i,x in enumerate(csv.fieldnames):
        csv.fieldnames[i] = x.strip().replace('  ',' ')

    for row in csv.rows:
        for i,x in enumerate(row):
            row[i] = x.strip().replace('  ',' ')


def remove_empty_rows(csv):
    def getemptyidx(csv):
        for i,row in enumerate(csv.rows):
            if ''.join(row) == '':
                return i
        return -1

    while True:
        idx = getemptyidx(csv)
        if idx == -1:
            return
        del csv.rows[idx]


def remove_rows_by_empty_column(csv, colname):
    def getemptyidx(csv, colidx):
        for i,row in enumerate(csv.rows):
            if row[colidx] == '':
                return i
        return -1

    colidx = csv.fieldnames.index(colname)
    if colidx < 0:
        error("Column %s not found in remove_rows_by_empty_column()." % colname)

    while True:
        idx = getemptyidx(csv, colidx)
        if idx == -1:
            return
        del csv.rows[idx]


# Removes rows that just contain things like "Bench" and "Ironman".
def remove_event_rows(csv):
    def geteventidx(csv):
        for i,row in enumerate(csv.rows):
            for k in row:
                k = k.lower()
                if k == 'total' or k == 'deadlift' or k == 'bench' or k == 'squat':
                    return i
                if k == 'bench only' or k == 'ironman' or k == 'deadlift only':
                    return i
        return -1

    while True:
        idx = geteventidx(csv)
        if idx == -1:
            return
        del csv.rows[idx]


def remove_stars(csv):
    for row in csv.rows:
        for i,x in enumerate(row):
            row[i] = x.replace('*','')


def remove_zeros(csv):
    for row in csv.rows:
        for i,x in enumerate(row):
            # The CSV conversion via LibreOffice already standardized
            # all decimal forms of 0.00 and such to just '0'.
            if x == '0':
                row[i] = ''


def standardize_fieldnames(csv):

    # If the first field is "Full Power", we can guess at some
    # of the other fieldnames, which are usually left blank.
    s = csv.fieldnames[0].lower()
    if 'full power' in s or 'saturday am' in s or 'ironman' in s or 'push' in s:
        # The next 6 fieldnames must be empty.
        if ''.join(csv.fieldnames[1:6]) != '':
            error("Field names expected to be blank, but aren't!")

        csv.fieldnames[0] = 'Sex'
        csv.fieldnames[1] = 'Class'
        csv.fieldnames[2] = 'Equipment'
        csv.fieldnames[3] = 'Division'
        csv.fieldnames[4] = 'WeightClassLBS'
        csv.fieldnames[5] = 'Name'

    for i,x in enumerate(csv.fieldnames):
        s = x.lower()
        if s == 'gender':
            x = 'Sex'
        elif s == 'class':
            x = 'Class' # TODO: What to do with this
        elif s == 'eq division':
            x = 'Equipment'
        elif s == 'age division':
            x = 'Division'
        elif s == 'wt' or s == 'wt class':
            x = 'WeightClassLBS'
        elif s == 'name' or s == 'powerlifter' or s == 'lifter name':
            x = 'Name'
        elif s == 'actual bwt.' or s == 'acutal b/w' or s == 'bwt' or s == 'actual bwt':
            x = 'BodyweightLBS'
        elif s == 'act. bwt' or s == 'act bwt' or s == 'btw' or s == 'act wt':
            x = 'BodyweightLBS'
        elif s == 'squat' or s == 'bestsquatlbs' or s == 'squart' or s == 'sq':
            x = 'BestSquatLBS'
        elif s == 'bench' or s == 'bestbenchlbs' or s == 'bp':
            x = 'BestBenchLBS'
        elif s == 'deadlift' or s == 'bestdeadliftlbs' or s == 'dl':
            x = 'BestDeadliftLBS'
        elif s == 'total' or s == 'totallbs':
            x = 'TotalLBS'
        elif s == 'place':
            x = 'Place'

        elif s == 'squat4lbs':
            x = 'Squat4LBS'
        elif s == 'bench4lbs':
            x = 'Bench4LBS'
        elif s == 'deadlift4lbs':
            x = 'Deadlift4LBS'

        elif s == 'sex':
            x = 'Sex'
        elif s == 'class':
            x = 'Class'
        elif s == 'equipment' or s == 'equip':
            x = 'Equipment'
        elif s == 'division':
            x = 'Division'
        elif s == 'weightclasslbs' or s == 'wclass':
            x = 'WeightClassLBS'
        elif s == 'weightclasskg':
            x = 'WeightClassKg'
        elif s == 'bodyweightlbs':
            x = 'BodyweightLBS'
        elif s == 'bodyweightkg':
            x = 'BodyweightKg'
        elif s == 'bestsquatkg':
            x = 'BestSquatKg'
        elif s == 'bestbenchkg':
            x = 'BestBenchKg'
        elif s == 'bestdeadliftkg':
            x = 'BestDeadliftKg'
        elif s == 'totalkg':
            x = 'TotalKg'
        elif s == 'squat4kg':
            x = 'Squat4Kg'
        elif s == 'bench4kg':
            x = 'Bench4Kg'
        elif s == 'deadlift4kg':
            x = 'Deadlift4Kg'
        elif s == 'state' or s == 'st':
            x = 'State'
        elif s == 'age':
            x = 'Age'
        else:
            error("Teach me what to do with column '%s'" % x)

        csv.fieldnames[i] = x


def fixequipment(csv):
    idx = csv.fieldnames.index('Equipment')
    if idx < 0:
        error("No Equipment column in fixequipment().")

    for row in csv.rows:
        s = row[idx].lower()
        # "Classic" means belt and wrist wraps only to the RPS.
        if s == 'raw classic' or s == 'raw clas' or s == 'raw c' or s == 'rc':
            x = 'Raw'
        # This one below looks the same, but actually has some unicode BS going on.
        elif s == 'raw clas' or s == 'raw classic' or s == 'raw' or s == 'raw -u':
            x = 'Raw'
        elif s == 'raw – u':
            x = 'Raw'

        # "Modern" allows wraps and sleeves for the squat and maybe the deadlift.
        # They track rankings for sleeves independently, but don't mark that anywhere.
        elif s == 'raw modern' or s == 'raw mod' or s == 'raw m' or s == 'rm':
            x = 'Wraps'

        elif s == 'single-ply' or s == 'single ply' or s == 'sp' or s == 'singleply':
            x = 'Single-ply'
        elif 'single' in s:
            x = 'Single-ply'

        elif s == 'multi-ply' or s == 'mulit-ply' or s == 'multi ply' or s == 'eq':
            x = 'Multi-ply'
        elif s == 'multiply' or s == 'mp' or s == 'multy ply' or s == 'gear':
            x = 'Multi-ply'
        elif 'multi' in s:
            x = 'Multi-ply'

        # This is used for benchers who have to choose between Raw or Wraps.
        # Seriously, though, what the hell?
        elif s == 'no choice made':
            x = 'Wraps'

        elif s == '':
            x = ''

        else:
            print("Full row: %s" % ','.join(row), file=sys.stderr)
            error("Teach fixequipment() what to do with '%s'" % s)

        row[idx] = x


def fixsex(csv):
    idx = csv.fieldnames.index('Sex')
    if idx < 0:
        error("No Sex column in fixsex().")

    for row in csv.rows:
        s = row[idx].lower()
        if s == 'male' or s == 'm' or s == 'men':
            x = 'M'
        elif s == 'female' or s == 'f' or s == 'women':
            x = 'F'
        else:
            error("Teach fixsex() what to do with '%s'" % s)

        row[idx] = x


def fixname(csv):
    idx = csv.fieldnames.index('Name')
    if idx < 0:
        error("No Name column in fixname().")

    for row in csv.rows:
        s = row[idx]
        s = s.replace('Jr.','Jr')
        s = s.replace('Sr.','Sr')

        # RPS uses this to look fancy in names like O'Brien.
        s = s.replace("’","'")

        # This is used to denote someone who entered amateur but totaled pro.
        s = s.replace("†","")

        # The first argument is some weird unicode space that keeps
        # creeping into the name field.
        s = s.replace("  "," ")
        s = s.replace("  "," ") # A second kind of weird space.
        s = s.replace(" "," ") # Yet more more space.

        # I'm not sure what this means, but it shows up in names.
        s = s.replace("NSB","")

        if s.upper() == s:
            error("Name looks all uppercase, needs manual fixing: '%s'" % s )

        for x in s.split():
            if x.lower() == x or x.upper() == x:
                # Except in names like "Louie de Leon" or for initials.
                if len(x.replace('.','')) > 2 and x != 'III':
                    error("Name needs proper casing: '%s'" % s)

        row[idx] = s.strip()


def fixclass(csv):
    idx = csv.fieldnames.index('Class')
    if idx < 0:
        error("No Class column in fixclass().")

    for row in csv.rows:
        s = row[idx].lower()
        if s == 'pro':
            x = 'Pro'
        elif s == 'am' or s == 'amateur' or s == 'ameteur' or s == 'am af':
            x = 'Amateur'
        elif s == 'elite' or s == 'elite am':
            x = 'Elite'
        elif s == 'military am' or s == 'military':
            x = 'Military Amateur'
        elif s == 'mil am':
            x = 'Military Amateur'
        elif s == 'police am' or s == 'pol am' or s == 'police':
            x = 'Police Amateur'
        elif s == 'police pro' or s == 'polce pro' or s == 'pol pro':
            x = 'Police Pro'
        elif s == 'military pro' or s == 'mil pro' or s == 'pro mil' or s == 'militarypro':
            x = 'Military Pro'
        elif s == 'crossfit' or s == 'cross fit':
            x = 'Crossfit'
        elif s == 'police/fire am':
            x = 'Police-Fire Amateur'

        elif s == 'junior pro':
            x = 'Junior Pro'
        elif s == 'pro/ police fire' or s == 'police/fire pro':
            x = 'Police-Fire Pro'

        else:
            error("Teach fixclass() what to do with '%s'" % s)

        row[idx] = x


def fixweightclass(csv):
    idx = csv.fieldnames.index('WeightClassLBS')
    if idx < 0:
        error("No WeightClassLBS column in fixweightclass().")
    sexidx = csv.fieldnames.index('Sex')
    if sexidx < 0:
        error("No Sex column in fixweightclass().")

    for row in csv.rows:
        if row[idx].lower() == 'shw':
            if row[sexidx] == 'M':
                row[idx] = '308+'
            elif row[sexidx] == 'F':
                row[idx] = '198+'
            else:
                error("Unknown sex in fixweightclass(): '%s'" % s)


def isnumber(s):
    try:
        float(s)
        return True
    except ValueError:
        return False


def fixplace(csv):
    idx = csv.fieldnames.index('Place')
    if idx < 0:
        error("No Place column in fixplace().")

    for row in csv.rows:
        x = row[idx]
        x = x.replace('pl','')
        x = x.replace('st','')
        x = x.replace('nd','')
        x = x.replace('rd','')
        x = x.replace('th','')
        x = x.strip()

        if not isnumber(x) and x != 'DQ':
            error("Unknown place in fixplace(): '%s'" % s)

        row[idx] = x


def fixlift(csv, liftfield):
    idx = csv.fieldnames.index(liftfield)
    if idx < 0:
        error("No %s column in fixlift()." % liftfield)

    # Get rid of things like 'bomb' and 'no lift'.
    for row in csv.rows:
        if not isnumber(row[idx]):
            row[idx] = ''


def mergeclassintodivision(csv):
    classidx = csv.fieldnames.index('Class')
    if classidx < 0:
        error("No Class column in mergeclassintodivision().")
    dividx = csv.fieldnames.index('Division')
    if dividx < 0:
        error("No Division column in mergeclassintodivision().")

    for row in csv.rows:
        x = "%s %s" % (row[classidx], row[dividx])
        row[dividx] = x.strip()

    csv.remove_column_by_index(classidx)


def main(filename):
    csv = Csv(filename)

    remove_stars(csv)
    strip_whitespace(csv)
    remove_empty_rows(csv)
    remove_event_rows(csv)
    remove_zeros(csv)
    standardize_fieldnames(csv)

    # Enable as temporary fix for broken files.
    #remove_rows_by_empty_column(csv, "Sex")

    if not 'Name' in csv.fieldnames:
        error("Couldn't find a name column.")
    if not 'Equipment' in csv.fieldnames:
        error("Couldn't find an equipment column.")
    if not 'Sex' in csv.fieldnames:
        error("Couldn't find a sex column.")

    fixequipment(csv)
    fixsex(csv)
    fixname(csv)
    fixclass(csv)

    # Depends on fixsex(), since it needs sex information for SHWs.
    if 'WeightClassLBS' in csv.fieldnames:
        fixweightclass(csv)

    # Depends on fixclass(), since it merges class into division.
    if 'Class' in csv.fieldnames and 'Division' in csv.fieldnames:
        mergeclassintodivision(csv)

    for f in csv.fieldnames:
        if 'Squat' in f or 'Bench' in f or 'Deadlift' in f or 'Total' in f:
            fixlift(csv, f)

    if 'Place' in csv.fieldnames:
        fixplace(csv)

    csv.write(sys.stdout)

        

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(" Usage: %s results.csv" % sys.argv[0], file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
