#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# CPF maintains a listing of all their meets on a single page.
#


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request


MEETSURL = "http://www.canadianpowerliftingfederation.com/meet-results/"
CPFDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def gethtml():
    with urllib.request.urlopen(MEETSURL) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    alist = soup.find_all("a", {"class": "btn"})

    urls = []
    for a in alist:
        if a.text != 'Register':
            urls.append(a['href'])

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(CPFDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                urls.append(fd.readline().strip())
    return urls


def main():
    html = gethtml()
    meetlist = getmeetlist(html)
    known = getenteredurls()

    for m in meetlist:
        if not m in known:
            print(color('[CPF] ') + m)

if __name__ == '__main__':
    main()
