#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# CPF maintains a listing of all their meets on a single page.
#

from bs4 import BeautifulSoup
import os
import sys

try:
    import oplprobe
except ModuleNotFoundError:
    sys.path.append(os.path.join(os.path.dirname(
        os.path.dirname(os.path.realpath(__file__))), "scripts"))
    import oplprobe


MEETSURL = "http://www.canadianpowerliftingfederation.com/meet-results/"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    alist = soup.find_all("a", {"class": "btn"})

    urls = []
    for a in alist:
        if a.text != 'Register':
            k = a['href'].strip()
            if k not in urls:
                urls.append(k)

    return urls


def main():
    meetlist = getmeetlist(oplprobe.gethtml(MEETSURL))
    entered = oplprobe.getenteredurls(FEDDIR)
    unentered = oplprobe.getunenteredurls(meetlist, entered)

    oplprobe.print_meets(color('[CPF]'), unentered)


if __name__ == '__main__':
    main()
