#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Given a BirthYear and a MeetDate, infer an Age range.
# An age range of x-y is represented as "x.5". So "27-28" would be "27.5".
# The web scripts can then read this number and render however is appropriate, like "~27".
#

from oplcsv import Csv
import sys


def getmeetdate(meetid, meetcsv):
    ididx = meetcsv.fieldnames.index('MeetID')
    dateidx = meetcsv.fieldnames.index('Date')

    for row in meetcsv.rows:
        if row[ididx] == meetid:
            return row[dateidx]

    print('Error: Could not find MeetID "%s".' % meetid)
    sys.exit(1)


def main(lifterfile, meetfile):
    meetcsv = Csv(meetfile)
    csv = Csv(lifterfile)

    if not 'BirthYear' in csv.fieldnames:
        sys.exit(0)

    if not 'Age' in csv.fieldnames:
        csv.append_column('Age')

    meetididx = csv.fieldnames.index('MeetID')
    birthyearidx = csv.fieldnames.index('BirthYear')
    ageidx = csv.fieldnames.index('Age')

    for row in csv.rows:
        if row[birthyearidx] and not row[ageidx]:
            date = getmeetdate(row[meetididx], meetcsv)
            [year,month,day] = date.split('-')

            lower_age = int(year) - int(row[birthyearidx])

            # Sanity checks.
            assert lower_age < 100
            assert lower_age > 3

            row[ageidx] = str(lower_age) + '.5'

    with open(lifterfile, 'w') as fd:
        csv.write(fd)


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: %s openpowerlifting.csv meets.csv' % sys.argv[0])
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
