#!/usr/bin/env python3

import oplcsv
import sys


def float2(s):
    if s == '':
        return 0.0
    s = s.replace(' ', '')
    return float(s)


def add_best_column(csv, lift, unit):
    idx = csv.index(lift + '3' + unit) + 1
    csv.insert_column(idx, 'Best3%s%s' % (lift, unit))

    idx1 = csv.index(lift + '1' + unit)
    idx2 = csv.index(lift + '2' + unit)
    idx3 = csv.index(lift + '3' + unit)

    for row in csv.rows:
        best = '0'
        for i in [idx1, idx2, idx3]:
            if float2(row[i]) > float2(best):
                best = row[i]

        if float2(best) > 0:
            row[idx] = best  # Keep as string.


def main(filename):
    csv = oplcsv.Csv(filename)

    if 'Squat1Kg' in csv.fieldnames and 'Best3SquatKg' not in csv.fieldnames:
        add_best_column(csv, 'Squat', 'Kg')
    if 'Bench1Kg' in csv.fieldnames and 'Best3BenchKg' not in csv.fieldnames:
        add_best_column(csv, 'Bench', 'Kg')
    if ('Deadlift1Kg' in csv.fieldnames
            and 'Best3DeadliftKg' not in csv.fieldnames):
        add_best_column(csv, 'Deadlift', 'Kg')

    if 'Squat1Lbs' in csv.fieldnames and 'Best3SquatLbs' not in csv.fieldnames:
        add_best_column(csv, 'Squat', 'Lbs')
    if 'Bench1Lbs' in csv.fieldnames and 'Best3BenchLbs' not in csv.fieldnames:
        add_best_column(csv, 'Bench', 'Lbs')
    if ('Deadlift1Lbs' in csv.fieldnames
            and 'Best3DeadliftLbs' not in csv.fieldnames):
        add_best_column(csv, 'Deadlift', 'Lbs')

    with open(filename, 'w') as fd:
        csv.write(fd)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: %s file.csv" % sys.argv[0], file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
