#!/usr/bin/env python3

import oplcsv
import sys


def getcategory(csv, row):
    if 'Division' in csv.fieldnames:
        dividx = csv.index('Division')
        div = row[dividx].lower()
    else:
        div = 'Open'

    eqidx = csv.index('Equipment')
    sexidx = csv.index('Sex')
    eventidx = csv.index('Event')
    if 'WeightClassKg' in csv.fieldnames:
        wtclsidx = csv.index('WeightClassKg')
    elif 'WeightClassLbs' in csv.fieldnames:
        wtclsidx = csv.index('WeightClassLbs')
    return (div, row[eqidx], row[sexidx], row[eventidx], row[wtclsidx])


def main(filename):
    csv = oplcsv.Csv(filename)

    if 'Place' in csv.fieldnames:
        print("There's already a place field.", file=sys.stderr)
        sys.exit(1)

    for i in ['Equipment', 'Sex', 'Event']:
        if i not in csv.fieldnames:
            print("Missing field: %s" % i, file=sys.stderr)
            sys.exit(1)

    if 'WeightClassKg' not in csv.fieldnames and 'WeightClassLbs' not in csv.fieldnames:
        print("Missing either WeightClassKg or WeightClassLbs field.", file=sys.stderr)
        sys.exit(1)

    if 'TotalKg' not in csv.fieldnames and 'TotalLbs' not in csv.fieldnames:
        print("Missing either TotalKg or TotalLbs field.", file=sys.stderr)
        sys.exit(1)

    csv.append_column('Place')

    placeidx = csv.index('Place')
    if 'TotalKg' in csv.fieldnames:
        totalidx = csv.index('TotalKg')
    elif 'TotalLbs' in csv.fieldnames:
        totalidx = csv.index('TotalLbs')

    if 'BodyweightKg' in csv.fieldnames:
        bwidx = csv.index('BodyweightKg')
    elif 'TotalKg' in csv.fieldnames:  # Equivalent to just ignoring bodyweight.
        bwidx = csv.index('TotalKg')
    elif 'TotalLbs' in csv.fieldnames:
        bwidx = csv.index('TotalLbs')

    categories = []
    for row in csv.rows:
        cat = getcategory(csv, row)
        if cat not in categories:
            categories.append(cat)

    for category in categories:
        lifters = []

        # Get a list of all the rows in this category that placed.
        for row in csv.rows:
            if getcategory(csv, row) == category:
                if not row[totalidx] or row[totalidx] == 0:
                    row[placeidx] = 'DQ'
                else:
                    lifters.append(row)

        # Order the rows by greatest total.
        # If total is the same, order within total by lowest bodyweight.
        lifters.sort(key=lambda x: (
            float(x[totalidx] or 0), -float(x[bwidx] or 999)), reverse=True)

        for i, row in enumerate(lifters):
            row[placeidx] = str(i + 1)

    # Mark Guest entries.
    for row in csv.rows:
        div = row[csv.index('Division')]
        if '-G' in div and row[totalidx]:
            row[placeidx] = 'G'

    with open(filename, 'w') as fd:
        csv.write(fd)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: %s file.csv" % sys.argv[0], file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
