#!/usr/bin/env python3
#
# Given a column named "CyrillicName" with a name in UTF-8,
# probably Cyrillic, transliterates the names into the Latin character set.
#

import oplcsv
import sys

# абвгдеёжзийклмнопрстуфхцчшщъьэюя

CyrillicMap = {
    'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'є': 'e',
    'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'і': 'i', 'й': 'y', 'к': 'k',
    'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's',
    'т': 't', 'у': 'u', 'ф': 'f', 'х': 'kh', 'ц': 'ts', 'ч': 'ch',
    'ш': 'sh', 'щ': 'shch', 'ъ': '', 'ь': '', 'э': 'e', 'ю': 'yu',
    'я': 'ya', 'ы': 'y',

    'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Є': 'E',
    'Ё': 'Yo', 'Ж': 'Zh', 'З': 'Z', 'И': 'I', 'І': 'I', 'Й': 'Y', 'К': 'K',
    'Л': 'L', 'М': 'M', 'Н': 'N', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S',
    'Т': 'T', 'У': 'U', 'Ф': 'F', 'Х': 'Kh', 'Ц': 'Ts', 'Ч': 'Ch',
    'Ш': 'Sh', 'Щ': 'Shch', 'Э': 'E', 'Ю': 'Yu', 'Я': 'Ya', 'Ы': 'Y'
}


def sub_from(m, c):
    try:
        return m[c]
    except KeyError:
        return c


def latinize(s):
    s = ''.join(list(map(lambda c: sub_from(CyrillicMap, c), s)))

    # Fix some common names.
    s = s.replace('Mukhammad', 'Muhammad')
    return s


def main(filename):
    csv = oplcsv.Csv(filename)

    if 'CyrillicName' not in csv.fieldnames:
        print('No CyrillicName column.')
        return

    if 'Name' not in csv.fieldnames:
        csv.insert_column(csv.index('CyrillicName'), 'Name')

    intlidx = csv.index('CyrillicName')
    nameidx = csv.index('Name')

    for row in csv.rows:
        if not row[nameidx]:
            row[nameidx] = latinize(row[intlidx])

    with open(filename, 'w') as fd:
        csv.write(fd)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: %s file.csv" % sys.argv[0], file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
