#!/bin/bash
#
# When called from the main project directory, compiles an SQLite version of the project.
#

set -e

DBFILE="build/openpowerlifting.sqlite3"

function require_dir {
	if ! [ -d "$1" ]; then
		echo "Error: Missing directory $1"
		exit 1
	fi
}

function require_file {
	if ! [ -f "$1" ]; then
		echo "Error: Missing file $1"
		exit 1
	fi
}

# Dependency checks.
require_dir "build"
require_file "build/sqlite-entries.csv"
require_file "build/sqlite-meets.csv"
require_file "build/sqlite-lifters.csv"

# If the database already exists, SQLite will add to existing tables
# instead of parsing the CSV headers. So the DB needs to be nuked.
rm -f "${DBFILE}"


# The column ordering is hardcoded and must agree with scripts/compile.
CREATEMEETSTABLE="
CREATE TABLE meets (
  MeetID INTEGER PRIMARY KEY NOT NULL,
  MeetPath TEXT UNIQUE NOT NULL,
  Federation TEXT NOT NULL,
  MeetDate DATE NOT NULL,
  MeetCountry TEXT NOT NULL,
  MeetState TEXT,
  MeetTown TEXT,
  MeetName TEXT NOT NULL
);
"

CREATEENTRIESTABLE="
CREATE TABLE entries (
  id INTEGER PRIMARY KEY NOT NULL,
  MeetID INTEGER NOT NULL,
  LifterID INTEGER NOT NULL,
  Sex BOOLEAN NOT NULL,
  Event CHAR(3),
  Equipment INTEGER NOT NULL,
  Age FLOAT,
  Division TEXT,
  BodyweightKg FLOAT,
  WeightClassKg FLOAT,
  Squat1Kg FLOAT,
  Squat2Kg FLOAT,
  Squat3Kg FLOAT,
  Squat4Kg FLOAT,
  BestSquatKg FLOAT,
  Bench1Kg FLOAT,
  Bench2Kg FLOAT,
  Bench3Kg FLOAT,
  Bench4Kg FLOAT,
  BestBenchKg FLOAT,
  Deadlift1Kg FLOAT,
  Deadlift2Kg FLOAT,
  Deadlift3Kg FLOAT,
  Deadlift4Kg FLOAT,
  BestDeadliftKg FLOAT,
  TotalKg FLOAT,
  Place TEXT,
  Wilks FLOAT,
  McCulloch FLOAT,

  FOREIGN KEY(MeetID) REFERENCES meets(MeetID),
  FOREIGN KEY(LifterID) REFERENCES lifters(LifterID)
);
"

CREATELIFTERSTABLE="
CREATE TABLE lifters (
  LifterID INTEGER PRIMARY KEY NOT NULL,
  Name TEXT NOT NULL,
  Username TEXT UNIQUE NOT NULL,
  Instagram TEXT
);
"

IMPORTCOMMAND="
PRAGMA foreign_keys = ON;
.mode csv

${CREATEMEETSTABLE}
.import build/sqlite-meets.csv meets

${CREATELIFTERSTABLE}
.import build/sqlite-lifters.csv lifters

${CREATEENTRIESTABLE}
.import build/sqlite-entries.csv entries

UPDATE lifters SET instagram = NULL WHERE instagram = '';
UPDATE meets SET state = NULL WHERE state = '';
UPDATE meets SET town = NULL WHERE town = '';
UPDATE entries SET event = NULL WHERE event = '';
UPDATE entries SET division = NULL WHERE division = '';
UPDATE entries SET place = NULL WHERE place = '';

vacuum;
"

echo "${IMPORTCOMMAND}" | sqlite3 "${DBFILE}"
