#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Remove columns with names from the provided list.
# The first row of the csvfile must contain column names.
#
# Overwrites the input file.
#

import sys
import re

if len(sys.argv) < 3:
    print(' Usage: %s csvfile col1 col2 ...', file=sys.stderr)
    sys.exit(1)

csvname = sys.argv[1]
columnsToRemove = sys.argv[2:]

with open(csvname) as fd:
    csv = [x.strip().split(',') for x in fd.readlines()]

while True:
    more_to_modify = False

    for i, header in enumerate(csv[0]):
        if header in columnsToRemove:
            more_to_modify = True
            break

    if not more_to_modify:
        break

    for row in csv:
        del row[i]

lines = [','.join(row) + "\n" for row in csv]

with open(csvname, 'w') as fd:
    fd.writelines(lines)
