#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Concatenates the CSV files given as arguments,
# where the first line of each CSV file specifies column names.
#
# Outputs to stdout.
#

from csv import Csv
import sys

if len(sys.argv) < 3:
    print(' Usage: %s csv1 csv2 ...' % sys.argv[0], file=sys.stderr)
    sys.exit(1)

csv = Csv(sys.argv[1])

for filename in sys.argv[2:]:
    c = Csv(filename)
    csv.cat(c)

csv.write_to(sys.stdout)
