#!/usr/bin/env python
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Converts every column with "LBS" in the header to kilograms,
# replacing "LBS" with "Kg".
# The first row must contain column names.
#
# Overwrites the input file if all columns can be converted.
#

import sys

# Round to two decimal places.
def internal_to_kg_string(s):
    try:
        return "{:.2f}".format(float(s) / 2.20462262)
    except ValueError:
        print >> sys.stderr, "Field not a float: \"%s\"" % s
        sys.exit(1)

def to_kg(s):
    if s[-1] is '+':
        return internal_to_kg_string(s[:-1]) + '+'

    return internal_to_kg_string(s)

if len(sys.argv) != 2:
    print >> sys.stderr, ' Usage: %s csvfile' % sys.argv[0]
    sys.exit(1)

(scriptname, csvname) = sys.argv

with open(csvname) as fd:
    csv = [x.strip().split(',') for x in fd.readlines()]

for j in xrange(0, len(csv[0])):
    if 'LBS' not in csv[0][j]:
        continue

    print ' Converting column "%s"' % csv[0][j]

    csv[0][j] = csv[0][j].replace('LBS', 'Kg')

    for i in xrange(1, len(csv)):
        # This doesn't really belong here, but just deal with it man ok?
        if 'SHW' in csv[i][j]:
            csv[i][j] = '308+'

        if csv[i][j]:
            csv[i][j] = to_kg(csv[i][j])

lines = [','.join(row) + "\n" for row in csv]

with open(csvname, 'w') as fd:
    fd.writelines(lines)
