#!/usr/bin/env python3

import sys

from oplcsv import Csv
from coefficient import wilks


def bounded_search(is_male, totalkg, target, lower, upper):
    delta = upper - lower
    if delta < 0.05:
        return upper

    mid = lower + delta / 2
    points = wilks(is_male, mid, totalkg)

    # Too many points -- increase the bodyweight.
    if points >= target:
        return bounded_search(is_male, totalkg, target, mid, upper)

    # Too few points -- lower the bodyweight.
    return bounded_search(is_male, totalkg, target, lower, mid)


# (bool, float, float, float) -> float
def calc_bw(is_male, wtcls, totalkg, target):
    points = wilks(is_male, wtcls, totalkg)

    # Too many points -- increase the bodyweight.
    if points >= target:
        return bounded_search(is_male, totalkg, target, wtcls, wtcls + 60)

    # Too few points -- lower the bodyweight.
    return bounded_search(is_male, totalkg, target, wtcls - 15, wtcls)


def main(filename):
    csv = Csv(filename)

    if 'BodyweightKg' not in csv.fieldnames:
        csv.append_column('BodyweightKg')
    bwidx = csv.index('BodyweightKg')

    sexidx = csv.index('Sex')
    wilksidx = csv.index('Wilks')
    wtclsidx = csv.index('WeightClassKg')
    totalkgidx = csv.index('TotalKg')

    for row in csv.rows:
        sex = row[sexidx]
        wilks = row[wilksidx]
        wtcls = row[wtclsidx]
        totalkg = row[totalkgidx]
        if '+' in wtcls:
            wtcls = wtcls.replace('+', '')

        if not sex or not wilks or not wtcls or not totalkg:
            continue

        row[bwidx] = str(calc_bw(sex == 'M', float(
            wtcls), float(totalkg), float(wilks)))

    with open(filename, 'w') as fd:
        csv.write(fd)


if __name__ == '__main__':
    main(sys.argv[1])
