#!/usr/bin/env python3
#
# Rounds all Kg lift columns to the nearest 0.5.

import sys
import oplcsv

csv = oplcsv.Csv(sys.argv[1])


# Round to two decimal places.
def internal_to_string(f):
    r = "{:.2f}".format(f)
    r = r.replace('.00', '')
    if '.' in r and r[-1] == '0':
        r = r[:-1]
    return r


def do_round(s):
    f = float(s)
    r = round(f * 2) / 2
    return internal_to_string(r)


def round_column(csv, idx):
    for row in csv.rows:
        if row[idx] != '':
            row[idx] = do_round(row[idx])


def main(filename):
    csv = oplcsv.Csv(filename)

    for field in csv.fieldnames:
        if 'Kg' in field and field not in ["WeightClassKg", "BodyweightKg"]:
            round_column(csv, csv.index(field))

    csv.write_filename(filename)


if __name__ == '__main__':
    main(sys.argv[1])
