#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# If the weight class column is provided but the bodyweight is not,
# sets the bodyweight equal to the class maximum, except for SHW.
#

from csv import Csv
import sys

if len(sys.argv) != 2:
    print(' Usage: %s csv' % sys.argv[0], file=sys.stderr)
    sys.exit(1)

csv = Csv(sys.argv[1])

assert 'WeightClassKg' in csv.fieldnames
assert 'BodyweightKg' in csv.fieldnames

widx = csv.fieldnames.index('WeightClassKg')
bidx = csv.fieldnames.index('BodyweightKg')

for row in csv.rows:
    if not row[bidx]:
        if row[widx] and not '+' in row[widx]:
            row[bidx] = row[widx]

with open(sys.argv[1], 'w') as fd:
    csv.write_to(fd)
