#!/usr/bin/env python

import sys

from pathlib import Path

for filename in sys.argv[1:]:
    file_path = Path(filename)
    with open(filename, "rb") as f:
        read_contents = f.read()
    write_contents = read_contents.replace(b"\r\n", b"\n")
    if read_contents != write_contents:
        with open(filename, "wb") as f:
            f.write(write_contents)
        print(f"Converted {filename} ✅")
    else:
        print(f"No CRLFs in {filename}, no change ❌")
