#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Looks for age divisions that are unknown

import oplcsv
import os
import sys


KNOWN_DIVISIONS = {
    # IPF
    "Sub-Juniors", "Juniors", "Master 1", "Master 2", "Master 3", "Master 4",
    # USAPL
    "Y1", "Y2", "Y3", "T1", "T2", "T3", "JR", "O",
    "M1a", "M1b", "M2a", "M3a", "M3b", "M4a", "M4b"
}


def find_divisions(unknown, entriespath):
    global KNOWN_DIVISIONS

    csv = oplcsv.Csv(entriespath)

    if 'Division' not in csv.fieldnames:
        return
    dividx = csv.index('Division')

    for row in csv.rows:
        if row[dividx] not in KNOWN_DIVISIONS:
            frequency = unknown.get(row[dividx])
            if frequency is not None:
                unknown[row[dividx]] = frequency + 1
            else:
                unknown[row[dividx]] = 1


def main(args):
    # Frequency dictionary for unknown divisions.
    unknown = {}

    for dirname, subdirs, files in os.walk(os.getcwd()):
        if "meet-data" in subdirs:
            subdirs[:] = ['meet-data']
        if 'entries.csv' in files:
            entriespath = dirname + os.sep + 'entries.csv'
            find_divisions(unknown, entriespath)

    if len(unknown) != 0:
        print(len(unknown), "unknown divisions!\n")

    # Convert dictionary to list.
    unknown_list = list(unknown.items())

    # Print unknown divisions sorted by frequency.
    for division in sorted(unknown_list, reverse=True, key=lambda x: x[1]):
        print(division[0], ":", division[1])


if __name__ == '__main__':
    main(sys.argv)
