#!/usr/bin/env python3

import oplcsv
import sys


def getcategory(csv, row):
    dividx = csv.index('Division')
    eqidx = csv.index('Equipment')
    sexidx = csv.index('Sex')
    eventidx = csv.index('Event')
    wtclsidx = csv.index('WeightClassKg')
    return (row[dividx], row[eqidx], row[sexidx], row[eventidx], row[wtclsidx])


def sortcategories(categories):

    def assigneq(eq):
        if eq == 'Raw':
            return 0
        if eq == 'Wraps':
            return 1
        if eq == 'Single-ply':
            return 2
        if eq == 'Multi-ply':
            return 3
        return 4

    def assignevent(evt):
        if evt == 'SBD':
            return 0
        if evt == 'S':
            return 1
        if evt == 'B':
            return 2
        if evt == 'BD':
            return 3
        if evt == 'D':
            return 4
        return 5

    def assignwtcls(wt):
        wt = wt.replace('+', '')
        return float(wt)

    categories.sort(key=lambda x:
                    (x[2],  # F always before M.
                     assignevent(x[3]),  # Then by event.
                     assigneq(x[1]),  # Within event, by equipment.
                        x[0],  # Within equipment, by division, alphabetically.
                        # Within division, by weight class, as float.
                        assignwtcls(x[4]),
                     )
                    )


def main(filename):
    csv = oplcsv.Csv(filename)

    for i in ['Division', 'Equipment', 'Sex', 'Event', 'BodyweightKg',
              'WeightClassKg', 'TotalKg']:
        if i not in csv.fieldnames:
            print("Missing field: %s" % i, file=sys.stderr)
            sys.exit(1)

    totalidx = csv.index('TotalKg')
    bwidx = csv.index('BodyweightKg')
    nameidx = csv.index('Name')
    bestsquatidx = csv.index('Best3SquatKg')
    bestbenchidx = csv.index('Best3BenchKg')
    bestdeadliftidx = csv.index('Best3DeadliftKg')
    totalidx = csv.index('TotalKg')
    wilksidx = csv.index('Wilks')

    categories = []
    for row in csv.rows:
        cat = getcategory(csv, row)
        if cat not in categories:
            categories.append(cat)

    sortcategories(categories)

    print('Place,Name,BodyweightKg,Best3SquatKg,Best3BenchKg,' \
          'Best3DeadliftKg,TotalKg,Wilks')

    for category in categories:
        lifters = []

        # Get a list of all the rows in this category that placed.
        for row in csv.rows:
            if getcategory(csv, row) == category:
                if row[totalidx]:
                    lifters.append(row)

        # Ignore DQs
        if len(lifters) == 0:
            continue

        # Order the rows by greatest total.
        # If total is the same, order within total by lowest bodyweight.
        lifters.sort(key=lambda x: (
            float(x[totalidx]), -float(x[bwidx])), reverse=True)

        (div, eq, sex, event, cls) = category

        if event == 'SBD':
            event = 'Powerlifting'
        elif event == 'B':
            event = 'Bench-Only'
        elif event == 'D':
            event = 'Deadlift-Only'

        if sex == 'M':
            sex = 'Men'
        elif sex == 'F':
            sex = 'Women'

        print(cls + 'kg', sex, div, eq, event)
        for i, row in enumerate(lifters):
            print(i + 1, ',', row[nameidx], ',', row[bwidx], ',',
                  row[bestsquatidx], ',', row[bestbenchidx], ',',
                  row[bestdeadliftidx], ',', row[totalidx], ',', row[wilksidx])
        print()


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: %s file.csv" % sys.argv[0], file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
