#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Given a file converted by pdf2txt, which therefore has pages
# separated by \f, output a different file for each page.
#
# This lets us use the nice importing tools of LibreOffice.
#

import sys

if len(sys.argv) != 2:
    print(' Usage: %s results.txt' % sys.argv[0], file=sys.stderr)
    sys.exit(1)

with open(sys.argv[1], 'r') as fd:
    pages = fd.read().split("\f")

for i, page in enumerate(pages):
    if not page.strip():
        continue
    filename = 'page%u.csv' % i
    with open(filename, 'w') as fd:
        fd.write(page)
