#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Simple script that uses a list of names and their misspellings
# to run over the Name column of all entries.csv files under the cwd,
# correcting names as it goes.
#
# Each data file is formatted with one lifter per line, with spellings
# separated by commas, the first spelling being the 'correct' one.
#
# NEW! Now handles CyrillicName.
# NEW! If $CWD is a subdirectory of meet-data, it only standardizes files
#      contained within that subdirectory. This is because recursing through
#      a directory is *extremely* slow on Windows Subsystem for Linux.
#
#
# NEW! Now handles GreekName.
#

import oplcsv
import os


# Creates a hashmap keyed on misspellings.
def load_names(datafilepath):
    h = {}
    with open(datafilepath, 'r', encoding='utf-8') as fd:
        for line in fd.readlines():
            names = line.split(',')
            assert len(names) >= 2

            correct_name = names[0].strip()
            assert correct_name

            for incorrect_name in names[1:]:
                incorrect_name = incorrect_name.strip()
                assert incorrect_name
                assert incorrect_name not in h
                h[incorrect_name] = correct_name

    return h


def correct_names(namehash, cyrhash, greekhash, entriespath):
    csv = oplcsv.Csv(entriespath)
    if 'Name' not in csv.fieldnames:
        RED = '\u001b[31m'
        RESET = '\u001b[0m'
        print(RED + entriespath + RESET)
        print(RED + "error: 'Name' column starts with an invisible character" + RESET)
    assert 'Name' in csv.fieldnames

    nameidx = csv.index('Name')
    cyridx = csv.index(
        'CyrillicName') if 'CyrillicName' in csv.fieldnames else None
    greekidx = csv.index(
        'GreekName') if 'GreekName' in csv.fieldnames else None

    changed = False
    for row in csv.rows:
        if row[nameidx] in namehash:
            changed = True
            row[nameidx] = namehash[row[nameidx]]
        if cyridx is not None and row[cyridx] in cyrhash:
            changed = True
            row[cyridx] = cyrhash[row[cyridx]]
        if greekidx is not None and row[greekidx] in greekhash:
            changed = True
            row[greekidx] = greekhash[row[greekidx]]
    if changed:
        with open(entriespath, 'w', encoding='utf-8', newline='\n') as fd:
            csv.write(fd)


def main():
    scriptsdir = os.path.dirname(os.path.realpath(__file__))
    projectdir = os.path.dirname(scriptsdir)
    liftersdir = projectdir + os.sep + "lifter-data"

    namehash = load_names(liftersdir + os.sep + "name-corrections.dat")
    cyrhash = load_names(liftersdir + os.sep + "cyrillic-name-corrections.dat")
    greekhash = load_names(liftersdir + os.sep + "greek-name-corrections.dat")

    # Standardize names only for files under the current subtree.
    #
    # This is a performance optimization for people adding new meets while
    # running on Windows Subsystem for Linux, which has very slow file operations.
    recursedir = os.getcwd()

    for dirname, subdirs, files in os.walk(recursedir):
        if "meet-data" in subdirs:
            subdirs[:] = ['meet-data']
        if 'entries.csv' in files:
            entriespath = dirname + os.sep + 'entries.csv'
            correct_names(namehash, cyrhash, greekhash, entriespath)


if __name__ == '__main__':
    main()
