#!/usr/bin/env python3

import os

from pathlib import Path

from oplcsv import Csv


def transform_name(name):

    ret_name_tokens = list()

    # McFoobar shouldn't normally become Mcfoobar
    name_tokens = name.title().split(' ')
    for name_token in name_tokens:
        ret_name_token = name_token.title()

        if ret_name_token.startswith("Mc"):
            ret_name_token = f"Mc{ret_name_token[2:].title()}"

        ret_name_tokens.append(ret_name_token)

    ret_name = ' '.join(ret_name_tokens)

    return ret_name


entries_path = Path(os.getcwd()) / "entries.csv"
entries_csv = Csv(entries_path)
entries_csv.transform_column_values_by_name("Name", transform_name)
entries_csv.write_filename(entries_path)
