#!/usr/bin/env python3

import os

from pathlib import Path

from oplcsv import Csv


# Define common name suffixes that should remain uppercase
SUFFIXES = {'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'}


def transform_name(name):
    ret_name_tokens = list()
    name_tokens = name.title().split(' ')

    for name_token in name_tokens:
        # Check if the current token is a suffix
        if name_token.upper() in SUFFIXES:
            ret_name_token = name_token.upper()
        else:
            ret_name_token = name_token.title()

            # McFoobar shouldn't normally become Mcfoobar
            if ret_name_token.startswith("Mc"):
                ret_name_token = f"Mc{ret_name_token[2:].title()}"

        ret_name_tokens.append(ret_name_token)

    ret_name = ' '.join(ret_name_tokens)

    return ret_name


entries_path = Path(os.getcwd()) / "entries.csv"
entries_csv = Csv(entries_path)
entries_csv.transform_column_values_by_name("Name", transform_name)
entries_csv.write_filename(entries_path)
