#!/bin/bash

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

# Use NASA-specific knowledge to parse results.csv into entries.csv.
${SCRIPTDIR}/nasa-standardize-csv results.csv > entries.csv

# Change 'X' in place to 'DQ'.
sed -i -e "s/^X,/DQ,/g" entries.csv

# Fix up SHW for the scripts below.
sed -i -e "s/,shw,/,SHW,/g" entries.csv

# Copy the template to the current directory for filling in.
cp ${SCRIPTDIR}/../meet.template meet.csv

# Convert WeightClassLBS and BodyweightLBS to Kg.
${REPOSCRIPTDIR}/csv-tokg entries.csv
${REPOSCRIPTDIR}/fix-weightclasses entries.csv

# Show any warnings.
${REPOSCRIPTDIR}/check-entries-csv entries.csv

echo "Done! Don't forget about meet.csv!"
