#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new meets from NASA.
# All the results are on one page!


from bs4 import BeautifulSoup
import os
import sys
import urllib.request


URLS = ["http://nasa-sports.com/meet-results-index/"]
BASEURL = "http://nasa-sports.com"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;33m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    content = soup.find_all("div", {"id": "content"})
    if len(content) == 0:
        error("Page layout seems to have changed.")
    elif len(content) > 1:
        error("Multiple result areas found.")

    urls = []
    for a in content[0].find_all('a'):
        url = a['href']
        if 'http' not in url:
            url = BASEURL + url
        if url not in urls:
            urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():
    quick = ('--quick' in sys.argv)

    meetlist = []
    for url in URLS:
        html = gethtml(url)
        meetlist = meetlist + getmeetlist(html)

    known = getenteredurls()

    count = 0
    for m in meetlist:
        if m not in known:
            count += 1
            if not quick or count <= 5:
                print(color('[NASA] ') + m)

    if count > 0:
        print(color('[NASA] ') + '%d meets remaining.' % count)


if __name__ == '__main__':
    main()
