#!/bin/bash

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSCRIPTDIR="${SCRIPTDIR}/../../scripts"

# Use NASA-specific knowledge to parse results.csv into lifters.csv.
${SCRIPTDIR}/nasa-standardize-csv results.csv > lifters.csv

# Copy the template to the current directory for filling in.
cp ${SCRIPTDIR}/../meet.template meet.csv

# Convert WeightClassLBS and BodyweightLBS to Kg.
${REPOSCRIPTDIR}/csv-tokg lifters.csv
${REPOSCRIPTDIR}/fix-weightclasses lifters.csv

# Show any warnings.
${REPOSCRIPTDIR}/check-lifters-csv lifters.csv

echo "Done! Don't forget about meet.csv!"
