//! Processing for the structs generated by the checker.

mod interpolate_age;
pub use interpolate_age::interpolate_age;

mod interpolate_country;
pub use interpolate_country::interpolate_country;

mod make_csv;
pub use make_csv::make_csv;
