//! Processing for the structs generated by the checker.

pub mod interpolate_ages;

mod interpolate_country;
pub use interpolate_country::interpolate_country;

mod make_csv;
pub use make_csv::make_csv;
