#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes the results page of Hercules Gym, which puts on its own meets.


from bs4 import BeautifulSoup
import datetime
import os
import shutil
import sys
import urllib.request


FEDDIR = os.path.dirname(os.path.realpath(__file__))
FEDURL = "http://herculesgym.net/meet_info.html"
BASEURL = "http://herculesgym.net"


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def color(s):
    return "\033[1;31m" + s + "\033[0;m"


def gethtml(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    events = soup.find_all("div", {"id": "section"})

    urls = []
    for e in events:
        for a in e.find_all('a'):
            url = a['href']

            # Hercules Gym malformats their URLs all over the place.
            if not url.startswith('/') and not 'herculesgym.net' in url:
                url = BASEURL + '/' + url
            elif url.startswith('/'):
                url = BASEURL + url

            # Should do this for all the federations, honestly.
            url = url.replace(' ', '%20')

            if not url in urls:  # Sometimes the entries show up twice.
                urls.append(url)

    return urls


def getenteredurls():
    urls = []
    for dirname, subdirs, files in os.walk(FEDDIR):
        if 'URL' in files:
            with open(dirname + os.sep + 'URL', 'r') as fd:
                for k in fd.readlines():
                    urls.append(k.strip())
    return urls


def main():

    html = gethtml(FEDURL)
    meetlist = getmeetlist(html)

    known = getenteredurls()

    for m in meetlist:
        if not m in known:
            print(color('[Hercules] ') + m)

if __name__ == '__main__':
    main()
