# Configuration for TTPF (Trinidad and Tobago)

[options]
    require_manual_disambiguation = true

[divisions]
    subjunior = {name="Sub-Junior", min=14, max=18.5}
    junior = {name="Junior", min=18.5, max=22.5}
    open = {name="Open", min=14, max=999}
    master1 = {name="Master 1", min=39.5, max=49.5}
    master2 = {name="Master 2", min=49.5, max=59.5}
    master3 = {name="Master 3", min=59.5, max=69.5}
    master4 = {name="Master 4", min=69.5, max=999}

    guest = {name="Guest", min=14, max=999}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range = ["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range = ["2021-01-01","9999-01-01"]
    sex = "F"

[exemptions]
