#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new Fédération Française de Force meets.
# Also checks the results archive.

from bs4 import BeautifulSoup
import os
import sys

try:
    import oplprobe
except ModuleNotFoundError:
    sys.path.append(os.path.join(os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.realpath(__file__)))), "scripts"))
    import oplprobe


RESULTS_URL = "http://www.ffforce.fr/tous-les-resultats/"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def color(s):
    return "\033[1;37m" + s + "\033[0;m"


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    main = soup.find_all("div", {"class": "main-content"})
    assert main, "No <div> element with class `main-content` found."

    links = main[0].find_all("a", {"class": "ligne_xls"})
    assert links, "No <a> elements with class `ligne_xls` found."

    return set(map(lambda link: link['href'].strip(), links))


def main():
    html_content = oplprobe.gethtml(RESULTS_URL)
    meets_list = getmeetlist(html_content)

    entered = oplprobe.getenteredurls(FEDDIR)
    unentered = oplprobe.getunenteredurls(meets_list, entered)

    oplprobe.print_meets(color('[FFForce]'), unentered)


if __name__ == '__main__':
    main()
