#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Import script for SVNL

from bs4 import BeautifulSoup
import errno
import os
import sys
import requests
import urllib.parse
import re

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 \
    (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}


try:
    from oplcsv import Csv
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.realpath(__file__)))), "scripts"))
    from oplcsv import Csv


def is_float(check_str):
    try:
        float(check_str)
        return True
    except ValueError:
        return False


def is_int(check_str):
    try:
        float(check_str)
        return check_str[-1] != '.' and float(check_str) % 1 == 0
    except ValueError:
        return False


def gethtml(url):
    return requests.get(url, headers=headers).content.decode('utf-8')


def error(msg):
    print(msg, file=sys.stderr)
    sys.exit(1)


def getdirname(url):
    return url.split('/')[-1]


def getresultsurl(url):
    html = requests.get(url, headers=headers).content.decode()

    soup = BeautifulSoup(html, 'html.parser')
    div = soup.find('div', {
                    'class': 'field-item even'})
    resultsurl = div.a['href']

    try:
        urllib.request.urlopen(resultsurl)
    except urllib.request.URLError:
        resultsurl = list(urllib.parse.urlsplit(resultsurl))
        resultsurl[2] = urllib.parse.quote(resultsurl[2])
        resultsurl = urllib.parse.urlunsplit(resultsurl)
        resultsurl = resultsurl.replace('http://', 'https://')
        resultsurl = resultsurl.replace('www.', '')

    try:
        urllib.request.urlopen(resultsurl)
    # Sometimes this url is wrong, if so use the usual url format
    except urllib.request.URLError:
        resultsurl = url.replace(
            '/tulokset/kansalliset-kilpailut', '').replace('/tulokset/sm-kilpailut', '')

    return resultsurl


def getmeetinfo(soup):
    csv = Csv()
    csv.fieldnames = ['Federation', 'Date', 'MeetCountry',
                      'MeetState', 'MeetTown', 'MeetName']

    # Get the facts table.
    tbody = soup.find('tbody')
    if len(tbody) == 0:
        error("Couldn't find the results table.")

    trs = tbody.find_all('tr')

    name = ''
    place = ''
    dotdate = ''

    date_line = 0

    for ii in range(2, len(trs)):
        if trs[ii].text.replace('.-', '-').count('.') == 2:
            date_line = ii
            break

    name = trs[date_line-1].find('td').text
    place_date = trs[date_line].find('td').text.strip()

    # Strip out time if it's given
    place_date = re.sub(
        r'(klo)( |\. )(\d{2}|\d)(:|\.)(\d{2}|\d)', '', place_date)
    place_date = re.sub(r'(klo)( |\. )(\d{2}|\d)', '', place_date)

    place_date = place_date.replace('La ', '')
    place_date = place_date.replace('. ', '.')
    place_date = place_date.replace(' i ', ' ')

    # Date is sometimes formatted DD/MM YYYY
    if '/' in place_date and place_date.count('.') < 2:
        place_date = re.sub(r'(?<=\/\d|\d{2}) ', '.', place_date, count=1)
        place_date = place_date.replace('/', '.')

    split_text = re.split("[, ]", place_date[::-1], maxsplit=1)
    split_text = [text[::-1]
                  for text in split_text if text.strip() != '' and not text.isupper()]

    if split_text[0].count('.') > 0:
        dotdate = split_text[0]
        place = ' '.join(split_text[1:])
    else:
        dotdate = split_text[-1]
        place = ' '.join(split_text[0:-1])

    # Sometimes year isn't given, try and find it in the title
    if dotdate.count('.') == 1 and not re.search(r'\d{4}', dotdate):
        title = soup.find('title').text
        year = re.search(r'\d{4}', title)
        dotdate = dotdate + '.' + year.group(0)

    # Old meets have the place below the date
    if place == '':
        [div, _] = get_division(trs[date_line-1].find('td').text)
        if div == '':  # Then this is probably a place
            place = trs[date_line-1].find('td').text
            # Set it blank so the script doesn't get confused later
            trs[date_line-1].string = ''

    # The date is formatted as dd.-dd.mm.yyyy.
    assert '.' in dotdate

    # If multiple days are given, remove the second
    # Dates spanning multiple months(sorry about how confusing this is)
    # Python doesn't support variable length look behind, hence the 4 lines
    dotdate = re.sub(r'(?<=\d{2}\.\d{2})\.-.*?\..*?(?=\.)', '', dotdate)
    dotdate = re.sub(r'(?<=\d{1}\.\d{2})\.-.*?\..*?(?=\.)', '', dotdate)
    dotdate = re.sub(r'(?<=\d{1}\.\d{1})\.-.*?\..*?(?=\.)', '', dotdate)
    dotdate = re.sub(r'(?<=\d{2}\.\d{1})\.-.*?\..*?(?=\.)', '', dotdate)
    dotdate = re.sub(r'\.-.*?(?=\.)', '', dotdate)  # Dates spanning one month

    # Clean up the name
    name = re.sub(r'\d{4}', '', name)
    name = name.replace(',', '')
    name = name.replace('\xa0', ' ')
    name = name.replace('  ', ' ')
    name = name.replace('  ', ' ')
    name = name.replace(' – ', ' - ')
    name = name.strip()

    # Clean up the place
    place = place.replace(',', '')
    place = place.strip()

    # Construct the date string
    [day, month, year] = dotdate.split('.')
    if len(day) == 1:
        day = '0'+day
    if len(month) == 1:
        month = '0'+month
    if len(year) == 2:
        if int(year) < 80:
            year = '19'+year
        else:
            year = '20'+year
    date = '%s-%s-%s' % (year.strip(), month.strip(), day.strip())
    date = date.replace(',', '')

    fed = 'SVNL'
    country = 'Finland'
    state = ''

    row = [fed, date, country, state, place, name]
    csv.rows = [row]

    return csv

# This is a very hacky way of padding the replacing colspans with blank tds


def expand_colspans(tr, enclosing_soup):
    tds = tr.find_all('td')
    for ii in range(len(tds)-1, -1, -1):
        if tds[ii].has_attr('colspan') and int(tds[ii]['colspan']) > 1:
            for jj in range(0, (int(tds[ii]['colspan'])-1)):
                blank_td = enclosing_soup.new_tag('td')
                tds[ii].insert_after(blank_td)
            del tds[ii]['colspan']

# Header is often split across multiple lines, fix this


def combine_header(trs):

    # Get the original soup object
    enclosing_soup = trs[0]
    while type(enclosing_soup) != BeautifulSoup:
        enclosing_soup = enclosing_soup.parent

    for ii in range(0, len(trs)):
        text = [x.text.strip()
                for x in trs[ii].find_all('td') if x.text.strip() != '']

        # Then this is probably a header
        if len(text) > 1:
            expand_colspans(trs[ii], enclosing_soup)
            expand_colspans(trs[ii+1], enclosing_soup)

            top_tds = trs[ii].find_all('td')
            bottom_tds = trs[ii+1].find_all('td')

            # Deal with rowspans
            for jj in range(0, len(top_tds)):
                if top_tds[jj].has_attr('rowspan') and int(top_tds[jj]['rowspan']) > 1:
                    blank_td = enclosing_soup.new_tag('td')
                    if jj < len(bottom_tds):
                        bottom_tds[jj].insert_before(blank_td)
                    else:
                        bottom_tds[-1].insert_after(blank_td)
                    del top_tds[jj]['rowspan']
                    bottom_tds = trs[ii+1].find_all('td')

            # Combine the header lines if they're split
            if (any('sij' in col.text.lower() for col in bottom_tds) or
                    bottom_tds[0].text.strip() == ''):
                for jj in range(0, min(len(bottom_tds), len(top_tds))):
                    top_tds[jj].string = top_tds[jj].text.strip(
                    ) + " " + bottom_tds[jj].text.strip()
                trs.pop(ii+1)
            break

    return trs


def getresults(soup, meet_name, url):
    csv = Csv()
    # Get the results table.
    tbody = soup.find('tbody')
    if len(tbody) == 0:
        error("Couldn't find the results table.")

    trs = tbody.find_all('tr')

    divstate = 'Open'
    sexstate = None

    # Find where the preamble ends
    start_data = 0
    for ii in range(2, len(trs)):
        if trs[ii].text.replace('.-', '-').count('.') == 2:
            start_data = ii
            break

    start_data += 1

    append_eqp = False
    append_sex = False

    meet_data = combine_header(trs[start_data:])

    sexstate = ''
    divstate = ''
    eqpstate = ''
    DivisionColumnIndex = None

    if 'miehet' in meet_name.lower() or 'miesten' in meet_name.lower():
        sexstate = 'M'
    elif 'naiset' in meet_name.lower() or 'naisten' in meet_name.lower():
        sexstate = 'F'

    if divstate == '':
        divstate = 'Open'

    for tr in meet_data:
        text = [x.text.strip()
                for x in tr.find_all('td') if x.text.strip() != '']
        # Skip blank and uninteresting rows
        if (len(text) == 0 or (len(text) == 1 and text[0].replace(',', '').isdigit())):
            continue

        # Sometimes there are some non-useful sentences about the meet written at the top
        if len(text) == 1 and len(text[0]) > 20:
            continue

        # Sometimes clubs/ cities are between rows,
        # probably need a better way of doing this
        if any(club_str in text[0].lower() for club_str in
               ['tukholma', 'tallinn', 'sotkamon visa',
                'kajaanin kuohu', 'stockholm', 'tnt', 'kp',
                'tap.erä', 'salvo', 'kavo', 'rayvo', 'tvn', 'uurame', 'äänekoski',
                'tammisaari', 'punkalaidun', 'ulkopuoliset', 'helsinki', 'helsingin']):
            continue

        # Exhibition lifters maybe?
        if text[0] == 'Näytöt':
            continue

        # Records are after data
        if (any(break_str in text[0].strip().lower() for break_str in
                ['ätykset', 'records', 'joukkuekilpailu', 'norbergs kraftsportförening',
                 'rekord:', 'domare:', 'tuomarit:', 'se:t'])):
            break

        # Skip record lines, this loses a small amount of division information
        # but it is not consistent whether it refers to the line above or below
        if (any(col in ['ME', 'SE', 'PE', 'SE/PE'] for col in text)
                and tr.find_all('td')[0].text.strip() != ''):
            continue

        # Header
        if any(name_str in ''.join(text).strip() for name_str in ['Name', 'Nimi']):
            if csv.fieldnames != []:
                continue
            iterable = iter(range(len(text)))

            # Get column information.
            for ii in iterable:
                h = text[ii].lower().replace('.', '')
                if h in ['sij', 'pl', 'place', 'paikka']:
                    csv.fieldnames += ['Place']
                elif h in ['m/w', 'm/n', 'nro', 'm/n *', 'n/n']:
                    csv.fieldnames += ['Sex']
                elif h == 'sarja' or h == 'cls' or h == 'class':
                    csv.fieldnames += ['WeightClassKg']
                    DivisionColumnIndex = ii
                elif h == 'paino' or h == 'bwt':
                    csv.fieldnames += ['BodyweightKg']
                elif 'nimi' in h or 'name' in h:
                    csv.fieldnames += ['Name']
                elif h == 'sv' or h == 'yob':
                    csv.fieldnames += ['BirthYear']
                elif h == 'seura' or h == 'club' or h == 'joukkue':
                    csv.fieldnames += ['Team']
                elif h == 'jk1' or h == 'jk 1':
                    csv.fieldnames += ['Squat1Kg']
                elif h == 'jk2' or h == 'jk 2':
                    csv.fieldnames += ['Squat2Kg']
                elif h == 'jk3' or h == 'jk 3':
                    csv.fieldnames += ['Squat3Kg']
                elif h == 'jk tul' or h == 'jk tulos' or h == 'sq result' or h == 'jk':
                    csv.fieldnames += ['Best3SquatKg']
                elif h == 'pp1' or h == 'pp 1':
                    csv.fieldnames += ['Bench1Kg']
                elif h == 'pp2' or h == 'pp 2':
                    csv.fieldnames += ['Bench2Kg']
                elif h == 'pp3' or h == 'pp 3':
                    csv.fieldnames += ['Bench3Kg']
                elif h == 'pp tul' or h == 'pp tulos' or h == 'bp result' or h == 'pp':
                    csv.fieldnames += ['Best3BenchKg']
                elif h == 'mn1' or h == 'mn 1':
                    csv.fieldnames += ['Deadlift1Kg']
                elif h == 'mn2' or h == 'mn 2':
                    csv.fieldnames += ['Deadlift2Kg']
                elif h == 'mn3' or h == 'mn 3':
                    csv.fieldnames += ['Deadlift3Kg']
                elif h == 'mn tul' or h == 'mn tulos' or h == 'dl result' or h == 'mn':
                    csv.fieldnames += ['Best3DeadliftKg']
                elif h in ['yt', 'tulos', 'yht', 'total', 'result',
                           'yht tulos', 'yhteis- tulos', 'yt / kg']:
                    csv.fieldnames += ['TotalKg']
                elif h in ['wilks', 'wpist', 'pist', 'wpts', 'wilks pist', 'wilks pts',
                           'ipf pist', 'ipf pts', 'ipf glp', 'ipf gl pist', 'gl pist',
                           'ipf gl pts', 'ipfgl', 'gl pts', 'ipf gl pisteet']:
                    csv.fieldnames += ['Wilks']
                elif h == 'jpist' or h == 'j pist':
                    csv.fieldnames += ['Points']
                elif h == 'nat':
                    csv.fieldnames += ['Country']
                elif h == 'squat 1' or h == 'jalkakyykky 1':
                    csv.fieldnames += ['Squat1Kg', 'Squat2Kg', 'Squat3Kg']
                    [next(iterable) for x in range(2)]
                elif h in ['bench press 1', 'penkkipunn 1', 'penkkipunnerrus 1']:
                    csv.fieldnames += ['Bench1Kg', 'Bench2Kg', 'Bench3Kg']
                    [next(iterable) for x in range(2)]
                elif h == 'deadlift 1' or h == 'maastanosto 1':
                    csv.fieldnames += ['Deadlift1Kg',
                                       'Deadlift2Kg', 'Deadlift3Kg']
                    [next(iterable) for x in range(2)]

                elif h == '1' and 'penkkip' in meet_name.lower():
                    csv.fieldnames += ['Bench1Kg']
                elif h == '2' and 'penkkip' in meet_name.lower():
                    csv.fieldnames += ['Bench2Kg']
                elif h == '3' and 'penkkip' in meet_name.lower():
                    csv.fieldnames += ['Bench3Kg']
                elif h == '4' and 'penkkip' in meet_name.lower():
                    csv.fieldnames += ['Bench4Kg']

                elif h == 'joukk tulos':
                    csv.fieldnames.append('IGNORE')
                elif h == 'joukk sij':
                    csv.fieldnames.append('IGNORE')
                elif h == 'ylip väh':
                    csv.fieldnames.append('IGNORE')

                else:
                    error("Unknown column name: \"%s\"" % h)

            csv.fieldnames += ['Division']

            if 'Sex' not in csv.fieldnames:
                append_sex = True

            # Classic meets and pre 2011 meets won't mark equipment
            # work it out contextually
            if 'Equipment' not in csv.fieldnames:
                append_eqp = True

        elif len(text) == 1:  # Division
            # Extract sex information.
            div_text = ''.join(text).strip().replace('-', '').lower()
            div_text = div_text.replace('kilpasarja', '')  # Powerlifting
            div_text = div_text.strip()

            if div_text != '':
                if 'naiset' in div_text or 'women' in div_text:
                    sexstate = 'F'
                    div_text = div_text.replace(
                        'naiset', '').replace('women', '').strip()
                    divstate = 'Open'
                elif 'miehet' in div_text or 'men' in div_text:
                    sexstate = 'M'
                    div_text = div_text.replace(
                        'miehet', '').replace('men', '').strip()
                    divstate = 'Open'
                elif div_text == 'n':
                    sexstate = 'F'
                    div_text = div_text[1:]
                elif div_text == 'm':
                    sexstate = 'M'
                    div_text = div_text[1:]
                elif div_text in ['klassinen', 'klassiskt']:
                    eqpstate = 'Raw'
                    div_text = div_text.replace('klassinen', '')
                    div_text = div_text.replace('klassiskt', '')
                elif div_text in ['varuste', 'varustevoimanosto', 'utrustat',
                                  'utrustning']:
                    eqpstate = 'Single-ply'
                    div_text = div_text.replace(
                        'varustevoimanosto', '').replace('varuste', '')
                    div_text = div_text.replace('utrustat', '')
                    div_text = div_text.replace('utrustning', '')

                if div_text.strip() != '':
                    # Extract division information.
                    [divstate, div_text] = get_division(div_text)

                    if len(div_text) != 0 and divstate == '':
                        error("Unknown state: \"%s\"" % div_text)

        elif (len(text) > 3 and 'Joukkueen tulos' not in text
                and 'Joukk. tulos' not in text):  # Lifter data

            # Accumulate the row, but we need to look at the class of each td
            # to figure out whether lifts were good or bad.
            lifter_data = []

            expand_colspans(tr, soup)

            col_idx = 0
            for td in tr.find_all('td'):
                col_text = td.text
                # Switch to dots for decimals
                col_text = col_text.replace(',', '.')

                # Remove Unicode spaces
                col_text = col_text.replace('\xa0', ' ')
                col_text = col_text.replace('\u200b', ' ')

                col_text = col_text.replace('\n', '')
                col_text = col_text.replace('\t', '')

                col_text = col_text.replace('*', '')
                col_text = col_text.replace('—–', '')

                # Failed lift.
                if ((td.s or td.strike or (td.has_attr('style') and
                                           'background-color: red' in td['style']
                                           ))
                        and col_text.strip() != ''):
                    col_text = '-' + col_text.strip()
                    col_text = col_text.replace('--', '-')
                elif (td.find('span') and td.span.has_attr('style') and
                      'text-decoration: line-through' in td.span['style']):
                    col_text = '-' + col_text.strip()
                    col_text = col_text.replace('--', '-')
                elif col_text == 'DSQ' or col_text == 'DNS':
                    col_text = ''

                # Skipped lift.
                if (len(col_text.strip()) > 1 and col_text.replace(' ', '').count('-')
                        == len(col_text.replace(' ', ''))):
                    col_text = ''

                if col_text.strip() == '…..':  # Skipped lift.
                    col_text = ''

                if is_float(col_text) and float(col_text) == 0.0:
                    col_text = ''

                # Removing trailing zeros
                if is_int(col_text.strip()):
                    col_text = col_text.replace('.00', '').replace('.0', '')

                lifter_data.append(col_text.strip().replace(
                    '  ', ' ').replace(',', ' '))
                if len(lifter_data) > len(csv.fieldnames)-1:
                    csv.fieldnames.insert(len(lifter_data) - 1, 'Extra')

                if col_idx == DivisionColumnIndex:
                    [divstate, div_text] = get_division(col_text)
                    pass
                col_idx = col_idx + 1

            lifter_data = lifter_data + [divstate]

            if append_sex:
                lifter_data = lifter_data + [sexstate]

            if append_eqp:
                lifter_data = lifter_data + [eqpstate]

            csv.rows += [lifter_data]

    if append_sex:
        csv.fieldnames += ['Sex']
    if append_eqp:
        csv.fieldnames += ['Equipment']

    return csv


# The place is reported as "1.", just remove the period.
def fixplace(csv):
    if 'Place' in csv.fieldnames:
        placeidx = csv.index('Place')
        totalidx = csv.index('TotalKg')
        for row in csv.rows:
            row[placeidx] = row[placeidx].replace('.', '')
            if row[placeidx] == '-' or row[placeidx] == '0' or row[placeidx] == '':
                row[placeidx] = 'DQ'
                row[totalidx] = ''  # Instead of a zero.
            elif 'ulkop' in row[placeidx].lower():  # Guest lifter, I think.
                row[placeidx] = 'G'
            elif row[placeidx].lower() == 'gäst':
                row[placeidx] = 'G'
            elif 'näyt' in row[placeidx].lower():
                row[placeidx] = 'G'


def fixequipment(csv, meetcsv):
    if 'Equipment' not in csv.fieldnames:
        return

    meet_name = meetcsv.rows[0][5]

    raw_meet = False

    if any(text in meet_name.lower() for text in ['klass', 'classic']):
        raw_meet = True

    eqidx = csv.index('Equipment')

    for row in csv.rows:
        if row[eqidx] == '':
            if raw_meet:
                row[eqidx] = 'Raw'
            else:
                if 'x' in row[eqidx]:
                    row[eqidx] = 'Raw'
                elif row[eqidx] == '':
                    row[eqidx] = 'Single-ply'
                else:
                    error("Unknown equipment: \"%s\"" % row[eqidx])

# Change M/N  and M/W to M/F


def fixsex(csv):
    sexidx = csv.index('Sex')
    eqpidx = csv.index('Equipment')
    for row in csv.rows:
        if row[sexidx] == 'N' or row[sexidx] == 'W':
            row[sexidx] = 'F'
        elif row[sexidx] in ['NKP', 'NKV', 'WCB']:
            row[sexidx] = 'F'
            row[eqpidx] = 'Raw'
        elif row[sexidx] in ['MKP', 'MKV', 'MCB']:
            row[sexidx] = 'M'
            row[eqpidx] = 'Raw'
        elif row[sexidx] in ['NVP', 'NVV']:
            row[sexidx] = 'F'
            row[eqpidx] = 'Single-ply'
        elif row[sexidx] in ['MVP', 'MVV', 'MEB']:
            row[sexidx] = 'M'
            row[eqpidx] = 'Single-ply'


def add_birthyear(csv):
    nameidx = csv.index('Name')

    if 'BirthYear' not in csv.fieldnames:
        for row in csv.rows:
            if 'Place' in csv.fieldnames:
                # Sometimes guest lifter is in brackets after birthyear
                if '(gästlyftare)' in row[nameidx]:
                    row[nameidx] = row[nameidx].replace('(gästlyftare)', '')
                    row[csv.index('Place')] = 'G'
                elif '(ulkop)' in row[nameidx]:
                    row[nameidx] = row[nameidx].replace('(ulkop)', '')
                    row[csv.index('Place')] = 'G'

            if '/' in row[nameidx]:
                [row[nameidx], birthyear] = row[nameidx].split('/')
                row[nameidx] = row[nameidx].strip()
                birthyear = birthyear.strip()

                if birthyear.isdigit() and len(birthyear) == 2:
                    if int(birthyear) < 20:  # Will need to be periodicaly updated
                        birthyear = '20' + birthyear
                    else:
                        birthyear = '19' + birthyear

                if 'BirthYear' not in csv.fieldnames:
                    csv.insert_column(len(csv.fieldnames), 'BirthYear')

                row[csv.index('BirthYear')] = birthyear

    else:  # We have a birthyear column, add century if it's not there
        byidx = csv.index('BirthYear')
        for row in csv.rows:
            if '/' in row[nameidx]:
                [row[nameidx], birthyear] = row[nameidx].split('/')
                row[nameidx] = row[nameidx].strip()

            if len(row[byidx]) == 2:  # Then we need to add the century

                if row[byidx] != '':
                    birthyear = row[byidx].strip()

                if birthyear.isdigit():
                    # Will need to be periodicaly updated
                    if int(birthyear) < 10 and len(birthyear) == 2:
                        birthyear = '20' + birthyear
                    else:
                        birthyear = '19' + birthyear

                row[byidx] = birthyear


def get_division(div_text):
    division = 'Open'
    if '14' in div_text:
        division = 'Under 14'
        div_text = div_text.replace('14', '')
    elif '15' in div_text:
        division = 'Under 15'
        div_text = div_text.replace('15', '')
    elif '17' in div_text:
        division = 'Under 17'
        div_text = div_text.replace('17', '')
    elif '18' in div_text:
        division = 'Under 18'
        div_text = div_text.replace('18', '')
    elif '20' in div_text[2:]:  # This case is for the -120kg weight class
        division = 'Under 20'
        div_text = div_text[:2]+div_text[2:].replace('20', '')
    elif div_text.strip() == '20':
        division = 'Under 20'
        div_text = div_text.replace('20', '')
    elif '23' in div_text:
        division = 'Under 23'
        div_text = div_text.replace('23', '')
    elif '40' in div_text:
        division = 'Over 40'
        div_text = div_text.replace('40+', '').replace('40', '')
    elif '50' in div_text:
        division = 'Over 50'
        div_text = div_text.replace('50', '')
    elif '60' in div_text:
        division = 'Over 60'
        div_text = div_text.replace('60', '')
    elif '70' in div_text:
        division = 'Over 70'
        div_text = div_text.replace('70', '')
    elif 'nuorten 20' in div_text:
        division = 'Under 20'
        div_text = div_text.replace('nuorten 20', '')
    elif 'nuorten 23' in div_text:
        division = 'Under 23'
        div_text = div_text.replace('nuorten 23', '')
    elif 'jun' in div_text:
        division = 'Under 23'
        div_text = div_text.replace('jun', '')
    elif 'as' in div_text:  # 'Klassien, miehet' ends here which is wrong!
        division = 'Over 40'
        div_text = div_text.replace('as', '')
    elif 'avoin' in div_text:
        division = 'Open'
        div_text = div_text.replace('avoin', '')
    elif 'toinen aste' in div_text:  # I think this is Juniors?
        division = 'Under 23'
        div_text = div_text.replace('toinen aste', '')
    elif 'korkeaaste' in div_text:  # I think this is Open
        division = 'Open'
        div_text = div_text.replace('korkeaaste', '')
    elif 'ulkopuolella' in div_text:  # Guest??
        division = 'Open'
        div_text = div_text.replace('ulkopuolella', '')
    elif 'vau' in div_text:  # Paralympic
        division = 'Paralympics'
        div_text = div_text.replace('vau', '')
    elif 'siu' in div_text:
        division = 'Open'
        div_text = div_text.replace('siu', '')
    elif 'veteraanien' in div_text:
        division = 'Over 40'
        div_text = div_text.replace('veteraanien', '')

    return [division, div_text.strip()]


def add_division(csv):
    if 'WeightClassKg' in csv.fieldnames:
        wcidx = csv.index('WeightClassKg')

        dividx = csv.index('Division')
        placeidx = csv.index('Place')
        sexidx = csv.index('Sex')
        for row in csv.rows:
            if row[wcidx] != '':
                if 'N' in row[wcidx]:
                    row[wcidx] = row[wcidx].replace('N', '')
                    row[sexidx] = 'F'
                elif 'M' in row[wcidx]:
                    row[wcidx] = row[wcidx].replace('M', '')
                    row[sexidx] = 'M'

                if row[wcidx][-1] == 'U':  # I think this is guest?
                    row[wcidx] = row[wcidx][:-1]
                    row[placeidx] = 'G'

                division = ''
                # Extract division information.
                if row[wcidx] != '60':
                    [division, row[wcidx]] = get_division(row[wcidx].lower())

                if division != '':
                    row[dividx] = division
                elif 'Extra' in csv.fieldnames:
                    [division, row[csv.index('Extra')]] = get_division(
                        row[csv.index('Extra')])
                    if division != '':
                        row[dividx] = division

                if 'Place' in csv.fieldnames:
                    placeidx = csv.index('Place')
                    if 'ulk.' in row[wcidx]:
                        row[placeidx] = 'G'
                        row[wcidx] = row[wcidx].replace('ulk.', '')
                    elif '(ulk)' in row[wcidx]:
                        row[placeidx] = 'G'
                        row[wcidx] = row[wcidx].replace('(ulk)', '')
                    elif 'ulk' in row[wcidx]:
                        row[placeidx] = 'G'
                        row[wcidx] = row[wcidx].replace('ulk', '')

                row[wcidx] = row[wcidx].strip()


def fixtotals(csv):
    if 'TotalKg' not in csv.fieldnames:
        csv.insert_column(len(csv.fieldnames), 'TotalKg')
        eventidx = csv.index('Event')
        for row in csv.rows:
            total = 0
            if 'S' in row[eventidx] and 'Best3SquatKg' in csv.fieldnames:
                if row[csv.index('Best3SquatKg')] in ['', 'out']:  # then lifter bombed
                    row[csv.index('Best3SquatKg')] = ''
                if row[csv.index('Best3SquatKg')] != "DSQ":
                    total += float(row[csv.index('Best3SquatKg')])
            elif 'B' in row[eventidx] and 'Best3BenchKg' in csv.fieldnames:
                if row[csv.index('Best3BenchKg')] in ['', 'out']:
                    row[csv.index('Best3BenchKg')] = ''
                    continue
                if row[csv.index('Best3BenchKg')] != 'DSQ':
                    total += float(row[csv.index('Best3BenchKg')])
            elif 'D' in row[eventidx] and 'Best3DeadliftKg' in csv.fieldnames:
                if row[csv.index('Best3DeadliftKg')] in ['', 'out']:
                    row[csv.index('Best3DeadliftKg')] = ''
                if row[csv.index('Best3DeadliftKg')] != 'DSQ':
                    total += float(row[csv.index('Best3DeadliftKg')])
            row[-1] = str(total)
    elif 'Place' in csv.fieldnames:
        totalidx = csv.index('TotalKg')
        placeidx = csv.index('Place')
        for row in csv.rows:
            row[totalidx] = row[totalidx].lower()
            if row[totalidx] == 'out' or row[totalidx] == 'disq':
                row[totalidx] = ''
                row[placeidx] = 'DQ'
            elif (row[totalidx] in ['out / d', 'dd'] or 'disq/d' in row[totalidx]
                    or 'disq / doping' in row[totalidx]):
                row[totalidx] = ''
                row[placeidx] = 'DD'


# Attempts are sometimes given, but not the Best3SquatKg columns, etc.
def calc_best_lift(csv, col, attemptlist):
    if col in csv.fieldnames:
        return

    for k in attemptlist:
        assert k in csv.fieldnames

    csv.insert_column(csv.index(attemptlist[-1]) + 1, col)

    for row in csv.rows:
        best = 0
        for k in attemptlist:
            try:
                attempt = float(row[csv.index(k)])
            except ValueError:
                attempt = 0
            if attempt > best:
                best = attempt
        if best > 0:
            row[csv.index(col)] = str(best)


def markevent(csv):
    assert 'Event' not in csv.fieldnames
    csv.append_column('Event')

    evtidx = csv.index('Event')

    def getevtindices(csv, fieldl):
        indexlist = []
        for f in fieldl:
            try:
                indexlist.append(csv.index(f))
            except ValueError:
                pass
        return indexlist

    squatidxl = getevtindices(
        csv, ['Squat1Kg', 'Squat2Kg', 'Squat3Kg', 'Best3SquatKg'])
    benchidxl = getevtindices(
        csv, ['Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Best3BenchKg'])
    deadliftidxl = getevtindices(
        csv, ['Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg', 'Best3DeadliftKg'])

    for row in csv.rows:
        evt = ''
        for i in squatidxl:
            if row[i] != '':
                evt = evt + 'S'
                break
        for i in benchidxl:
            if row[i] != '':
                evt = evt + 'B'
                break
        for i in deadliftidxl:
            if row[i] != '':
                evt = evt + 'D'
                break
        row[evtidx] = evt


def is_sex_empty(csv):
    byidx = csv.index('Sex')
    for row in csv.rows:
        if row[byidx]:
            return False
        else:
            print('Sex column is empty')
            return True


def remove_empty_and_ignore_cols(csv):
    def iscolempty(csv, i):
        for row in csv.rows:
            if row[i]:
                return False
        return True

    def getemptyidx(csv):
        for i, col in enumerate(csv.fieldnames):
            if iscolempty(csv, i):
                return i
        return -1

    # Remove all the columns named 'IGNORE'
    while 'IGNORE' in csv.fieldnames:
        csv.remove_column_by_name('IGNORE')

    while True:
        idx = getemptyidx(csv)
        if idx == -1:
            return
        csv.remove_column_by_index(idx)


def sex_from_weightclass(csv):
    female_classes = ['52', '57', '63', '69', '76', '84', '84+']
    male_classes = ['59', '66', '74', '83', '93', '105', '120', '120+']
    sexidx = csv.index('Sex')
    weightclassidx = csv.index('WeightClassKg')
    for row in csv.rows:
        if row[weightclassidx] in female_classes:
            row[sexidx] = 'F'
        elif row[weightclassidx] in male_classes:
            row[sexidx] = 'M'
        else:
            pass
            # Probably shouldn't get here unless rules change


def main(dirname, url):

    # Get the results page from the page linked in the lists
    # results_url = getresultsurl(url)

    # if 'arvokilpailut' in url:
    #     error("Script can't handle international meets")
    # elif 'kansalliset-kilpailut' not in url and 'sm-kilpailu' not in url:
    #     error('Script expects urls from the results list, not the results themselves')
    html = gethtml(url)

    soup = BeautifulSoup(html, 'html.parser')

    meetcsv = getmeetinfo(soup)
    entriescsv = getresults(
        soup, meetcsv.rows[0][meetcsv.index('MeetName')], url)
    if len(entriescsv.rows) == 0:
        error("No rows found!")

    fixequipment(entriescsv, meetcsv)
    add_birthyear(entriescsv)
    add_division(entriescsv)
    fixsex(entriescsv)

    if is_sex_empty(entriescsv):
        sex_from_weightclass(entriescsv)
    remove_empty_and_ignore_cols(entriescsv)
    entriescsv.append_column('BirthDate')

    # Wilks will be automatically calculated later.
    # Feds get it wrong all the time.
    if 'Wilks' in entriescsv.fieldnames:
        entriescsv.remove_column_by_name('Wilks')

    if 'Points' in entriescsv.fieldnames:
        entriescsv.remove_column_by_name('Points')

    if 'Extra' in entriescsv.fieldnames:
        entriescsv.remove_column_by_name('Extra')

    if ('Squat1Kg' in entriescsv.fieldnames and
            'Best3SquatKg' not in entriescsv.fieldnames):
        calc_best_lift(entriescsv, 'Best3SquatKg', [
                       'Squat1Kg', 'Squat2Kg', 'Squat3Kg'])
    if ('Bench1Kg' in entriescsv.fieldnames and
            'Best3BenchKg' not in entriescsv.fieldnames):
        calc_best_lift(entriescsv, 'Best3BenchKg', [
                       'Bench1Kg', 'Bench2Kg', 'Bench3Kg'])
    if ('Deadlift1Kg' in entriescsv.fieldnames and
            'Best3DeadliftKg' not in entriescsv.fieldnames):
        calc_best_lift(entriescsv, 'Best3DeadliftKg', [
                       'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg'])

    # Figure out event information.
    markevent(entriescsv)

    fixtotals(entriescsv)
    fixplace(entriescsv)

    # Remove things in brackets from name,
    # we do this here so as to not miss classic meets when assigning equipment
    meetcsv.rows[0][meetcsv.index('MeetName')] = re.sub(
        r'\(.*\)', '', meetcsv.rows[0][meetcsv.index('MeetName')])
    meetcsv.rows[0][meetcsv.index(
        'MeetName')] = meetcsv.rows[0][meetcsv.index('MeetName')].strip()

    try:
        os.makedirs(dirname)
    except OSError as exception:
        if exception.errno != errno.EEXIST:
            raise
        else:
            error("Directory '%s' already exists." % dirname)

    with open(dirname + os.sep + 'entries.csv', 'w', encoding='utf-8') as fd:
        entriescsv.write(fd)
    with open(dirname + os.sep + 'meet.csv', 'w', encoding='utf-8') as fd:
        meetcsv.write(fd)
    with open(dirname + os.sep + 'URL', 'w') as fd:
        fd.write(url + "\n")

    print("Imported into %s." % dirname)


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: %s dirname url" % sys.argv[0])
    main(sys.argv[1], sys.argv[2])
