# Configuration for ProRaw.

[options]
    require_manual_disambiguation = true

[rulesets.default]
    ruleset = ["CombineAllEquipment"]
    date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    # ProRaw does not have age divisions.

    open = {name="Open", min=0, max=999, equipment=["Raw","Wraps"]}

    mor = {name="M-OR", min=0, max=999, sex="M", equipment=["Raw","Wraps"]}
    for = {name="F-OR", min=0, max=999, sex="F", equipment=["Raw","Wraps"]}

[weightclasses.pre-15_M]
    classes = ["80","95","110","125","125+"]
    date_range = ["2011-01-01","2025-01-01"]
    sex = "M"

# ProRaw XV moved 80 to 85
[weightclasses.default_M]
    classes = ["85","95","110","125","125+"]
    date_range = ["2025-01-01","9999-12-31"]
    sex = "M"

[weightclasses.pre_13_F]
    classes = ["60","75","75+"]
    date_range = ["2011-01-01","2023-01-01"]
    sex = "F"

# ProRaw 13 added women's 90kg
[weightclasses.13-14_F]
    classes = ["60","75","90","90+"]
    date_range = ["2023-01-01","2025-01-01"]
    sex = "F"

# ProRaw XV moved 60 to 65
[weightclasses.default_F]
    classes = ["65","75","90","90+"]
    date_range = ["2025-01-01","9999-12-31"]
    sex = "F"

[exemptions]
    001 = ["ExemptWeightClassConsistency"] # Women had no weightclasses.
    002 = ["ExemptWeightClassConsistency"] # Women had no weightclasses.
    003 = ["ExemptWeightClassConsistency"] # Women had no weightclasses.
    004 = ["ExemptWeightClassConsistency"] # Women had no weightclasses.
    005 = ["ExemptWeightClassConsistency"] # Women had no weightclasses.
    006 = ["ExemptWeightClassConsistency"] # No weight information for Bench-only.
    007 = ["ExemptWeightClassConsistency"] # Non-SBD uses traditional weightclasses.
    008 = ["ExemptWeightClassConsistency"] # Non-SBD uses traditional weightclasses.
    009 = ["ExemptWeightClassConsistency"] # Non-SBD uses traditional weightclasses.
    010 = ["ExemptWeightClassConsistency"] # Non-SBD uses traditional weightclasses.
    011 = ["ExemptWeightClassConsistency"] # Non-SBD uses traditional weightclasses.
    012-sleeves-single = ["ExemptWeightClassConsistency"] # Sleeves and non-SBD uses traditional weightclasses.
    013-sleeves = ["ExemptWeightClassConsistency"] # Sleeves uses traditional weightclasses. 

    # For early BigDogs meets, lifters were assumed to weight 140+ instead of 125+,
    # so that their records would count for the 140+ class.
    bigdogs = ["ExemptWeightClassConsistency"] # All lifters assumed 140+
    bigdogs2 = ["ExemptWeightClassConsistency"] # All lifters assumed 140+
    bigdogs4 = ["ExemptWeightClassConsistency"] # Omit weight classes.
    bigdogs5 = ["ExemptWeightClassConsistency"] # Omit weight classes.
