# Configuration for the FRPL.
# https://www.romaniapowerlifting.ro/wp-content/uploads/2019/03/Regulamentul_de_organizare_a_activitatii_de_powerlifting_2019.pdf

[divisions]
    open = {name = "Open", min=14, max=999}
    soi = {name = "SOI", min=14, max=999}
    junior2 = {name = "Junior II", min=12, max=17.5}
    junior1 = {name = "Junior I", min=18.5, max=22.5}
    master1 = {name = "Master I", min=39.5, max=48.5}
    master2 = {name = "Master II", min=49.5, max=58.5}
    master3 = {name = "Master III", min=59.5, max=68.5}
    master4 = {name = "Master IV", min=69.5, max=999} # No weightclasses.

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.year2020_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2020-12-31"]
    sex = "F"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-12-31"]
    sex = "F"

[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Junior I","Junior II"]

[weightclasses.year2020_junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","2020-12-31"]
    sex = "F"
    divisions = ["Junior I","Junior II"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-12-31"]
    sex = "F"
    divisions = ["Junior I","Junior II"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[exemptions]
    1603 = ["ExemptDivision"] #~10 year old in Junior II