#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Simple script to run over a list of names and output any
# that are listed as being both M and F.
#
import sys
import os

try:
    import oplcsv
except ModuleNotFoundError:
    sys.path.append(os.path.join(os.path.dirname(
        os.path.dirname(os.path.realpath(__file__))), "scripts"))
    import oplcsv


def assign_wc(filename):
    csv = oplcsv.Csv(filename)

    if 'WeightClassKg' not in csv.fieldnames:
        csv.append_column('WeightClassKg')



    wcidx = csv.index('WeightClassKg')
    bwidx = csv.index('BodyweightKg')
    sexidx = csv.index('Sex')
    dividx = csv.index('Division')
    for row in csv.rows:
        if row[wcidx] == '' and row[bwidx] != '':
            sex = row[sexidx]
            bw = float(row[bwidx])

            # if sex == 'M':
            #     if bw <= 52:
            #         row[wcidx] = '52'
            #     elif bw <= 56:
            #         row[wcidx] = '56'
            #     elif bw <= 60:
            #         row[wcidx] = '60'
            #     elif bw <= 67.5:
            #         row[wcidx] = '67.5'
            #     elif bw <= 75:
            #         row[wcidx] = '75'
            #     elif bw <= 82.5:
            #         row[wcidx] = '82.5'
            #     elif bw <= 90:
            #         row[wcidx] = '90'
            #     elif bw <= 100:
            #         row[wcidx] = '100'
            #     elif bw <= 110:
            #         row[wcidx] = '110'
            #     elif bw <= 125:
            #         row[wcidx] = '125'
            #     else:
            #         row[wcidx] = '125+'
            # else:
            #     if bw <= 44:
            #         row[wcidx] = '44'
            #     elif bw <= 48:
            #         row[wcidx] = '48'
            #     if bw <= 52:
            #         row[wcidx] = '52'
            #     elif bw <= 56:
            #         row[wcidx] = '56'
            #     elif bw <= 60:
            #         row[wcidx] = '60'
            #     elif bw <= 67.5:
            #         row[wcidx] = '67.5'
            #     elif bw <= 75:
            #         row[wcidx] = '75'
            #     elif bw <= 82.5:
            #         row[wcidx] = '82.5'
            #     elif bw <= 90:
            #         row[wcidx] = '90'
            #     else:
            #         row[wcidx] = '90+'

            if sex == 'M':
                if bw <= 59:
                    row[wcidx] = '529'
                elif bw <= 66:
                    row[wcidx] = '66'
                elif bw <= 74:
                    row[wcidx] = '74'
                elif bw <= 83:
                    row[wcidx] = '83'
                elif bw <= 93:
                    row[wcidx] = '93'
                elif bw <= 105:
                    row[wcidx] = '105'
                elif bw <= 120:
                    row[wcidx] = '120'
                else:
                    row[wcidx] = '120+'
            else:
                if bw <= 47:
                    row[wcidx] = '47'
                elif bw <= 52:
                    row[wcidx] = '52'
                if bw <= 57:
                    row[wcidx] = '57'
                elif bw <= 63:
                    row[wcidx] = '63'
                elif bw <= 72:
                    row[wcidx] = '72'
                elif bw <= 84:
                    row[wcidx] = '84'
                else:
                    row[wcidx] = '84+'



        if row[dividx] == 'Over 40':
            row[dividx] == 'Open'

    with open(filename, 'w') as fd:
        csv.write(fd)



def main():

    if len(sys.argv) > 1:
        assign_wc(sys.argv[1])



if __name__ == '__main__':
    sys.exit(main())
