#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Simple script to run over a list of names and output any
# that are listed as being both M and F.
#
import sys
import os

try:
    import oplcsv
except ModuleNotFoundError:
    sys.path.append(os.path.join(os.path.dirname(
        os.path.dirname(os.path.realpath(__file__))), "scripts"))
    import oplcsv
import re


# Hashtable for sex lookup.
# str -> [int, int] (left for male, right for female).
NameToSexHash = {}

###############################################

errorCount = 0
warningCount = 0


def redden(s):
    if os.name != 'nt':
        return "\033[1;31m" + s + "\033[0;m"
    return s


def enyellow(s):
    if os.name != 'nt':
        return "\033[1;33m" + s + "\033[0;m"
    return s


def perror(s):
    global errorCount
    errorCount += 1
    print(' ' + redden(s), file=sys.stderr)


def pwarning(s):
    global warningCount
    warningCount += 1
    print(' ' + enyellow(s), file=sys.stderr)

###############################################


def cleanup(filename):

    csv = oplcsv.Csv(filename)

    dateidx = csv.index('Date')
    nameidx = csv.index('MeetName')
    townidx = csv.index('MeetTown')

    if csv.rows[0][nameidx] != '' and( csv.rows[0][nameidx].isdigit() or csv.rows[0][nameidx] == ' '):
        csv.rows[0][nameidx] = csv.rows[0][nameidx][1:]
    csv.rows[0][townidx] = csv.rows[0][townidx].title()

    csv.rows[0][nameidx] = csv.rows[0][nameidx].title().replace('\xa0',' ')
    csv.rows[0][nameidx] = re.sub('\d{4}','',csv.rows[0][nameidx])
    csv.rows[0][nameidx] = csv.rows[0][nameidx].strip()
    csv.rows[0][nameidx] = csv.rows[0][nameidx].replace('()','')
    csv.rows[0][nameidx]= csv.rows[0][nameidx].replace('  ',' ')
    if csv.rows[0][dateidx] != '':
        [year,month,day]=csv.rows[0][dateidx].split('-')
        month = month.strip()
        day = day.strip()

        if len(month) == 1:
            month = '0'+month
        if len(day) == 1:
            day = '0'+day

        csv.rows[0][dateidx] = year+'-'+month+'-'+day

    print(csv.rows)
    with open(filename, 'w') as fd:
        csv.write(fd)



def main():
    for dirname, subdirs, files in os.walk(os.getcwd()):
        if 'meet.csv' in files:
            meetpath = dirname + os.sep + 'meet.csv'
            cleanup(meetpath)



if __name__ == '__main__':
    sys.exit(main())
