#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Simple script to run over a list of names and output any
# that are listed as being both M and F.
#
import sys
import os

try:
    import oplcsv
except ModuleNotFoundError:
    sys.path.append(os.path.join(os.path.dirname(
        os.path.dirname(os.path.realpath(__file__))), "scripts"))
    import oplcsv
import re


# Hashtable for sex lookup.
# str -> [int, int] (left for male, right for female).
NameToSexHash = {}

###############################################

errorCount = 0
warningCount = 0


def redden(s):
    if os.name != 'nt':
        return "\033[1;31m" + s + "\033[0;m"
    return s


def enyellow(s):
    if os.name != 'nt':
        return "\033[1;33m" + s + "\033[0;m"
    return s


def perror(s):
    global errorCount
    errorCount += 1
    print(' ' + redden(s), file=sys.stderr)


def pwarning(s):
    global warningCount
    warningCount += 1
    print(' ' + enyellow(s), file=sys.stderr)

###############################################



def main():
    for dirname, subdirs, files in os.walk(os.getcwd()):
        if 'meet.csv' in files:
            meetpath = dirname + os.sep + 'meet.csv'

            meetcsv = oplcsv.Csv(meetpath)
            meetyear = meetcsv.rows[0][1].split('-')[0]
            meetyear = meetyear[2:]

            ii = 1
            meet_id = meetyear + '01'
            while os.path.exists(os.path.dirname(dirname)+os.sep+meet_id):
                ii +=1
                if ii < 10:
                    meet_id = meetyear+'0'+str(ii)
                else:
                    meet_id = meetyear + str(ii)
            os.rename(dirname,os.path.dirname(dirname)+os.sep+meet_id)


if __name__ == '__main__':
    sys.exit(main())
