#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Generates CSS rules that allow the federation selector to work.

import bisect
import html
import oplcsv
import sys

LIFTERSCSV = '../build/openpowerlifting.csv'
MEETCSV = '../build/meets.csv'


def main():
    csv = oplcsv.Csv(MEETCSV)

    # Get a list of all federations.
    fedidx = csv.fieldnames.index('Federation')

    feds = []
    for row in csv.rows:
        if row[fedidx] not in feds:
            feds.append(row[fedidx])

    # First output rules that hide all federations if there's an active selector.
    print('table.selectorActive tr{display:none;}')

    # Then output a rule that shows a federation if it's been selected.
    # Since these rules come later, they will override the other ones.
    for fed in feds:
        print('table.%s tr.%s{display:table-row}' % (fed,fed))

    # Rule to always show these rows (used for the header).
    print('table tr.alwaysShow{display:table-row}')

if __name__ == '__main__':
    main()
