#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Generates a static table of meet information.
#

import bisect
import oplcsv
import sys

LIFTERSCSV = '../build/openpowerlifting.csv'
MEETCSV = '../build/meets.csv'


# Gets some row that contains the given meetid, using a super ham-fisted binary search.
def findsomelifterin(meetid, lifterscsv):
    meetidx = lifterscsv.fieldnames.index('MeetID')
    rows = lifterscsv.rows

    meetid = int(meetid)

    x = int(len(rows) / 2)
    step = int(len(rows) / 4)
    while int(rows[x][meetidx]) != meetid:
        if int(rows[x][meetidx]) < meetid:
            x = x + step
        else:
            x = x - step

        # In edge cases, just keep stepping by one. It's fast enough.
        step = max(1, int(step / 2))
        
    return x


# Knowing that the lifterscsv rows are in sorted order by MeetID,
# perform a binary search and expand to grab nearby rows.
def getliftersfor(meetid, lifterscsv):
    meetidx = lifterscsv.fieldnames.index('MeetID')

    # Bisect to find one of the lifters.
    x = findsomelifterin(meetid, lifterscsv)

    # The rest of the lifters are above and below that one.
    # Find the lowest and highest indices for lifters in this meet, inclusive.
    lowest = x
    while lowest > 0:
        if lifterscsv.rows[lowest-1][meetidx] != meetid:
            break
        lowest = lowest - 1

    highest = x
    while highest < len(lifterscsv.rows) - 1:
        if lifterscsv.rows[highest+1][meetidx] != meetid:
            break
        highest = highest + 1

    return lifterscsv.rows[lowest : highest + 1]


def main():
    csv = oplcsv.Csv(MEETCSV)

    meetidx = csv.fieldnames.index('MeetID')
    fedidx = csv.fieldnames.index('Federation')
    dateidx = csv.fieldnames.index('Date')
    countryidx = csv.fieldnames.index('MeetCountry')
    stateidx = csv.fieldnames.index('MeetState')
    townidx = csv.fieldnames.index('MeetTown')
    meetnameidx = csv.fieldnames.index('MeetName')

    # By default, sort the list by date, most recent meets first.
    csv.rows = sorted(csv.rows, key=lambda x : x[dateidx], reverse=True)

    lifters = oplcsv.Csv(LIFTERSCSV)
    liftersmeetidx = lifters.fieldnames.index('MeetID')
    lifterswilksidx = lifters.fieldnames.index('Wilks')
    liftersnameidx = lifters.fieldnames.index('Name')

    print('<table>')
    print('<thead>')
    print('<tr><td>Federation</td><td>Date</td><td>Location</td><td>Town</td><td>Name</td><td>Lifters</td>')
    print('<td>Best Lifter</td><td>Best Wilks</td></tr>')
    print('</thead>')
    print('<tbody>')
    for row in csv.rows:
        # How many lifters competed?
        results = getliftersfor(row[meetidx], lifters)
        results = sorted(results, key=lambda x : float(x[lifterswilksidx] or 0.0), reverse=True)

        # TODO: Might need Best Raw (incl/wraps) / Best Geared (incl/multi).

        # Lifters who entered multiple events should only count once.
        names = []
        for k in results:
            if not k[liftersnameidx] in names:
                names.append(k[liftersnameidx])

        location = row[countryidx]
        if row[stateidx]:
            location = "%s-%s" % (row[countryidx], row[stateidx])

        bestlifter = results[0][liftersnameidx]
        bestwilks = results[0][lifterswilksidx]
        if not bestwilks:
            lifterhtml = ''
        else:
            lifterhtml = '<a href="lifters.html?q=%s">%s</a>' % (bestlifter, bestlifter)

        print('<tr>')
        print('<td>%s</td>' % row[fedidx])
        print('<td>%s</td>' % row[dateidx])
        print('<td>%s</td>' % location)
        print('<td>%s</td>' % row[townidx])
        print('<td>%s</td>' % row[meetnameidx])
        print('<td>%d</td>' % len(names))
        print('<td>%s</td>' % lifterhtml)
        print('<td>%s</td>' % bestwilks)
        print('</tr>')

    print('</tbody>')
    print('</table>')


if __name__ == '__main__':
    main()
