#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Generates the top site navigation part of the HTML page.
# Argument must be one of the site parts.

import datetime
import locale
import sys
sys.path.append('../scripts')
import oplcsv


def showdbstats():
    locale.setlocale(locale.LC_ALL, 'en_US.utf8')
    csv = oplcsv.Csv('../build/openpowerlifting.csv')
    meets = oplcsv.Csv('../build/meets.csv')

    num_entries = locale.format('%d', len(csv.rows), grouping=True)
    num_meets = locale.format('%d', len(meets.rows), grouping=True)
    compiledate = datetime.datetime.now().strftime("%Y-%m-%d")

    print(' (%s Entries; %s Meets; Updated %s)' % (num_entries, num_meets, compiledate))

def addnav(activetab, tab, title):
    active = 'nav__link--active' if activetab == tab else ''
    print('<a href="{0}.html" class="nav__link {1}">{2}</a>'.format(tab, active, title))

def main(activetab):
    print('<div id="header">')
    print('OpenPowerlifting')
    print('<div class="nav">')

    print('<a href="https://instagram.com/openpowerlifting" class="nav__link"><i class="fa fa-instagram"></i></a>')
    print('<a href="https://facebook.com/openpowerlifting" class=" nav__link"><i class="fa fa-facebook"></i></a>')

    assert activetab in ['rankings', 'lifters', 'meet', 'meetlist', 'data', 'contact']

    addnav(activetab, 'index', 'Rankings')
    addnav(activetab, 'meetlist', 'Meets')
    addnav(activetab, 'data', 'Data')
    addnav(activetab, 'contact', 'Contact')

    print('<a href="https://www.patreon.com/openpowerlifting" class="nav__link">Support Us</a>')
    print('<a href="https://www.patreon.com/openpowerlifting">\
             <img style="height: 15px; width: 15px" \
                  src="images/patreon_navigation_logo_mini_orange.png"/>\
           </a>')

    print('</div>')
    print('<div class="header__stats">')
    showdbstats()
    print('</div>')
    print('</div>')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: %s tabname" % sys.argv[0], file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
