#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Generates the top site navigation part of the HTML page.
# Argument must be one of the site parts.
#

import datetime
import locale
import oplcsv
import sys


def showdbstats():
    locale.setlocale(locale.LC_ALL, 'en_US')
    csv = oplcsv.Csv('../build/openpowerlifting.csv')
    meets = oplcsv.Csv('../build/meets.csv')

    entries = locale.format('%d', len(csv.rows), grouping=True)
    compiledate = datetime.datetime.now().strftime("%Y-%m-%d")

    print(' (%s Entries, Updated %s)' % (entries, compiledate))


def main(tabname):

    print('<div id="header">')
    print('OpenPowerlifting &mdash;')

    print('<div class="nav">')

    assert tabname in ['rankings', 'lifters', 'meet', 'meetlist', 'downloads', 'contact']

    if tabname == 'rankings':
        print('<a href="index.html" class="nav__link nav__link--active">Rankings</a>')
    else:
        print('<a href="index.html" class="nav__link">Rankings</a>')

    if tabname == 'meetlist':
        print('<a href="meetlist.html" class="nav__link nav__link--active">Meets</a>')
    else:
        print('<a href="meetlist.html" class="nav__link">Meets</a>')

    if tabname == 'downloads':
        print('<a href="downloads.html" class="nav__link nav__link--active">Downloads</a>')
    else:
        print('<a href="downloads.html" class="nav__link">Downloads</a>')

    if tabname == 'contact':
        print('<a href="contact.html" class="nav__link nav__link--active">Contact</a>')
    else:
        print('<a href="contact.html" class="nav__link">Contact</a>')

    print('</div>')

    print('<div class="header__stats">')

    showdbstats()

    print('</div>')

    print('</div>')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: %s tabname" % sys.argv[0], file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1])
