#!/usr/bin/bash
# Gets the human-readable filesize for the provided argument.
# Used by downloads.html to report download size.

if [ $# -ne 1 ]; then
	echo "Usage: %0 filename"
	exit 1
fi

if [ ! -f "$1" ]; then
	echo "Error: File \"$1\" doesn't exist"
	exit 1
fi

du -h "$1" | cut -f 1
