#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Translates the social-instagram.csv file into social-media.js,
# a dictionary (Name -> Array) lookup table for mapping lifters
# to social media accounts.
#

import sys
import os

try:
    import oplcsv
except:
    sys.path.append(os.path.abspath(os.path.join(
        os.path.dirname(__file__), '..', 'scripts')))
    import oplcsv


SOCIALFILE = '../lifter-data/social-instagram.csv'


def main():
    csv = oplcsv.Csv(SOCIALFILE)
    assert csv.fieldnames[0] == 'Name'

    for i, field in enumerate(csv.fieldnames[1:]):
        print('var socialmedia_%s = %d;' % (field, i))

    print('var socialmedia = (function() {')
    print('var s = {};')

    for row in csv.rows:
        print('s["%s"] = ["%s"];' % (row[0], row[1]))

    print('return s;')
    print('})();')


if __name__ == '__main__':
    main()
